### ISSUE TITLE
vm.create  segmentation violation 

### ISSUE THREAD

**Issue by perfecto25** [vmware/govmomi#1035]
Hello, having some issues creating VMs in our vCenter (6.5.0)

govc version 
0.16.0

running a basic vm create, all my GOVC params are sourced,

```
[mike@mrxmaster2:vmreaper]$ govc vm.create -net.adapter=vmxnet3 -c=2 -disk=60G -g otherGuest64 -m 2048 -on=false njofisheye01

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9da71d]

goroutine 1 [running]:
github.com/vmware/govmomi/object.DistributedVirtualPortgroup.EthernetCardBackingInfo(0xc42031a820, 0x13, 0xc420168840, 0xc42031a340, 0x1b, 0xc420312cf0, 0x10, 0x18ad580, 0xc4200140d8, 0x0, ...)
        /home/vmware/release/src/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go:47 +0x24d
github.com/vmware/govmomi/object.(*DistributedVirtualPortgroup).EthernetCardBackingInfo(0xc42037f680, 0x18ad580, 0xc4200140d8, 0x0, 0x0, 0x2a8, 0x10256c0)
        <autogenerated>:1 +0x7e
github.com/vmware/govmomi/govc/flags.(*NetworkFlag).Device(0xc4201b1ab0, 0x0, 0xc42033d9a8, 0xc420485610, 0x412f2d)
        /home/vmware/release/src/github.com/vmware/govmomi/govc/flags/network.go:114 +0x7f
github.com/vmware/govmomi/govc/vm.(*create).addNetwork(0xc4201bab40, 0xc420448320, 0x2, 0x2, 0xc420448320, 0x2, 0x2, 0x0, 0x0)
        /home/vmware/release/src/github.com/vmware/govmomi/govc/vm/create.go:435 +0x33
github.com/vmware/govmomi/govc/vm.(*create).createVM(0xc4201bab40, 0x18ad580, 0xc4200140d0, 0x0, 0x0, 0xc420057d30)
        /home/vmware/release/src/github.com/vmware/govmomi/govc/vm/create.go:306 +0x15c
github.com/vmware/govmomi/govc/vm.(*create).Run(0xc4201bab40, 0x18ad580, 0xc4200140d0, 0xc420064540, 0x0, 0x0)
        /home/vmware/release/src/github.com/vmware/govmomi/govc/vm/create.go:262 +0x2cc
github.com/vmware/govmomi/govc/cli.Run(0xc4200100c0, 0xa, 0xa, 0xc88700)
        /home/vmware/release/src/github.com/vmware/govmomi/govc/cli/command.go:156 +0x522
main.main()
        /home/vmware/release/src/github.com/vmware/govmomi/govc/main.go:82 +0x63
```

whats weird is that I used to be able to create VMs before, I tried this both w govc 0.12 and 0.16 and same result. Wondering ifs something to do with our vCenter version, we recently upgraded from 5.5 to 6.5, but it doesnt look like its even communicating w vCenter at the stage where it breaks down.

**Comment by perfecto25** [comment]
result,

wondering if this has to do with vCenter permissions for the user that Im logging in as, I had to add permissions to Network object for this user. I can login to vCenter as this user and browse the Network tree, so it should be ok

```
types.ObjectUpdate{
    Kind:      "enter",
    Obj:       types.ManagedObjectReference{Type:"DistributedVirtualPortgroup", Value:"dvportgroup-2189"},
    ChangeSet: []types.PropertyChange{
        {
            Name: "alarmActionsEnabled",
            Op:   "assign",
            Val:  bool(true),
        },
        {
            Name: "availableField",
            Op:   "assign",
            Val:  types.ArrayOfCustomFieldDef{},
        },
        {
            Name: "config",
            Op:   "assign",
            Val:  types.DVPortgroupConfigInfo{
                Key:                      "dvportgroup-2189",
                Name:                     "NJO",
                NumPorts:                 164,
                DistributedVirtualSwitch: (*types.ManagedObjectReference)(nil),
                DefaultPortConfig:        &types.VMwareDVSPortSetting{
                    DVPortSetting: types.DVPortSetting{
                        Blocked: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                        VmDirectPathGen2Allowed: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                        InShapingPolicy: &types.DVSTrafficShapingPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Enabled: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: types.NewBool(false),
                            },
                            AverageBandwidth: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 100000000,
                            },
                            PeakBandwidth: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 100000000,
                            },
                            BurstSize: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 104857600,
                            },
                        },
                        OutShapingPolicy: &types.DVSTrafficShapingPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Enabled: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: types.NewBool(false),
                            },
                            AverageBandwidth: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 100000000,
                            },
                            PeakBandwidth: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 100000000,
                            },
                            BurstSize: &types.LongPolicy{
                                InheritablePolicy: types.InheritablePolicy{
                                    Inherited: true,
                                },
                                Value: 104857600,
                            },
                        },
                        VendorSpecificConfig: &types.DVSVendorSpecificConfig{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            KeyValue: nil,
                        },
                        NetworkResourcePoolKey: &types.StringPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: "-1",
                        },
                        FilterPolicy: &types.DvsFilterPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            FilterConfig: nil,
                        },
                    },
                    Vlan: &types.VmwareDistributedVirtualSwitchVlanIdSpec{
                        VmwareDistributedVirtualSwitchVlanSpec: types.VmwareDistributedVirtualSwitchVlanSpec{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                        },
                        VlanId: 0,
                    },
                    QosTag: &types.IntPolicy{
                        InheritablePolicy: types.InheritablePolicy{
                            Inherited: true,
                        },
                        Value: -1,
                    },
                    UplinkTeamingPolicy: &types.VmwareUplinkPortTeamingPolicy{
                        InheritablePolicy: types.InheritablePolicy{},
                        Policy:            &types.StringPolicy{
                            InheritablePolicy: types.InheritablePolicy{},
                            Value:             "loadbalance_srcid",
                        },
                        ReversePolicy: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{},
                            Value:             types.NewBool(true),
                        },
                        NotifySwitches: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{},
                            Value:             types.NewBool(true),
                        },
                        RollingOrder: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{},
                            Value:             types.NewBool(false),
                        },
                        FailureCriteria: &types.DVSFailureCriteria{
                            InheritablePolicy: types.InheritablePolicy{},
                            CheckSpeed:        &types.StringPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             "minimum",
                            },
                            Speed: &types.IntPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             10,
                            },
                            CheckDuplex: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             types.NewBool(false),
                            },
                            FullDuplex: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             types.NewBool(false),
                            },
                            CheckErrorPercent: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             types.NewBool(false),
                            },
                            Percentage:  &types.IntPolicy{},
                            CheckBeacon: &types.BoolPolicy{
                                InheritablePolicy: types.InheritablePolicy{},
                                Value:             types.NewBool(false),
                            },
                        },
                        UplinkPortOrder: &types.VMwareUplinkPortOrderPolicy{
                            InheritablePolicy: types.InheritablePolicy{},
                            ActiveUplinkPort:  []string{"Uplink 1"},
                            StandbyUplinkPort: []string{"Uplink 2"},
                        },
                    },
                    SecurityPolicy: &types.DVSSecurityPolicy{
                        InheritablePolicy: types.InheritablePolicy{
                            Inherited: true,
                        },
                        AllowPromiscuous: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                        MacChanges: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                        ForgedTransmits: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                    },
                    IpfixEnabled: &types.BoolPolicy{
                        InheritablePolicy: types.InheritablePolicy{
                            Inherited: true,
                        },
                        Value: types.NewBool(false),
                    },
                    TxUplink: &types.BoolPolicy{
                        InheritablePolicy: types.InheritablePolicy{
                            Inherited: true,
                        },
                        Value: types.NewBool(false),
                    },
                    LacpPolicy: &types.VMwareUplinkLacpPolicy{
                        InheritablePolicy: types.InheritablePolicy{
                            Inherited: true,
                        },
                        Enable: &types.BoolPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: types.NewBool(false),
                        },
                        Mode: &types.StringPolicy{
                            InheritablePolicy: types.InheritablePolicy{
                                Inherited: true,
                            },
                            Value: "passive",
                        },
                    },
                },
                Description: "",
                Type:        "earlyBinding",
                Policy:      &types.VMwareDVSPortgroupPolicy{
                    DVPortgroupPolicy: types.DVPortgroupPolicy{
                        BlockOverrideAllowed:               true,
                        ShapingOverrideAllowed:             false,
                        VendorConfigOverrideAllowed:        false,
                        LivePortMovingAllowed:              false,
                        PortConfigResetAtDisconnect:        true,
                        NetworkResourcePoolOverrideAllowed: types.NewBool(false),
                        TrafficFilterOverrideAllowed:       types.NewBool(false),
                    },
                    VlanOverrideAllowed:           false,
                    UplinkTeamingOverrideAllowed:  false,
                    SecurityPolicyOverrideAllowed: false,
                    IpfixOverrideAllowed:          types.NewBool(false),
                },
                PortNameFormat:               "",
                Scope:                        nil,
                VendorSpecificConfig:         nil,
                ConfigVersion:                "9",
                AutoExpand:                   types.NewBool(true),
                VmVnicNetworkResourcePoolKey: "",
                Uplink:                       types.NewBool(false),
            },
        },
        {
            Name: "configIssue",
            Op:   "assign",
            Val:  types.ArrayOfEvent{},
        },
        {
            Name: "configStatus",
            Op:   "assign",
            Val:  "green",
        },
        {
            Name: "customValue",
            Op:   "assign",
            Val:  types.ArrayOfCustomFieldValue{},
        },
        {
            Name: "declaredAlarmState",
            Op:   "assign",
            Val:  types.ArrayOfAlarmState{},
        },
        {
            Name: "disabledMethod",
            Op:   "assign",
            Val:  types.ArrayOfString{},
        },
        {
            Name: "effectiveRole",
            Op:   "assign",
            Val:  types.ArrayOfInt{
                Int: []int32{855638118},
            },
        },
        {
            Name: "host",
            Op:   "assign",
            Val:  types.ArrayOfManagedObjectReference{
                ManagedObjectReference: []types.ManagedObjectReference{
                    {Type:"HostSystem", Value:"host-84"},
                    {Type:"HostSystem", Value:"host-2165"},
                    {Type:"HostSystem", Value:"host-100"},
                    {Type:"HostSystem", Value:"host-111"},
                    {Type:"HostSystem", Value:"host-2158"},
                    {Type:"HostSystem", Value:"host-682"},
                    {Type:"HostSystem", Value:"host-2161"},
                    {Type:"HostSystem", Value:"host-2163"},
                },
            },
        },
        {
            Name: "key",
            Op:   "assign",
            Val:  "dvportgroup-2189",
        },
        {
            Name: "name",
            Op:   "assign",
            Val:  "NJO",
        },
        {
            Name: "overallStatus",
            Op:   "assign",
            Val:  "green",
        },
        {
            Name: "parent",
            Op:   "assign",
            Val:  types.ManagedObjectReference{Type:"Folder", Value:"group-n2128"},
        },
        {
            Name: "permission",
            Op:   "assign",
            Val:  types.ArrayOfPermission{
                Permission: []types.Permission{
                    {
                        Entity:    &types.ManagedObjectReference{Type:"DistributedVirtualPortgroup", Value:"dvportgroup-2189"},
                        Principal: "VSPHERE.LOCAL\\vagrant",
                        Group:     false,
                        RoleId:    855638118,
                        Propagate: false,
                    },
                },
            },
        },
        {
            Name: "portKeys",
            Op:   "assign",
            Val:  types.ArrayOfString{
                String: []string{"0", "1", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "2", "24", "25", "256", "257", "258", "259", "26", "260", "261", "262", "263", "264", "265", "266", "267", "268", "27", "272", "273", "274", "275", "28", "280", "281", "282", "288", "289", "29", "290", "291", "292", "293", "296", "297", "298", "299", "3", "30", "300", "301", "31", "32", "328", "329", "33", "330", "331", "332", "333", "334", "335", "336", "337", "338", "339", "340", "341", "342", "343", "344", "345", "346", "35", "36", "37", "38", "39", "4", "40", "41", "42", "43", "44", "45", "47", "48", "49", "5", "50", "51", "52", "53", "54", "55", "57", "58", "6", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "7", "70", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "97", "98"},
            },
        },
        {
            Name: "recentTask",
            Op:   "assign",
            Val:  types.ArrayOfManagedObjectReference{},
        },
        {
            Name: "summary",
            Op:   "assign",
            Val:  types.NetworkSummary{
                Network:    &types.ManagedObjectReference{Type:"DistributedVirtualPortgroup", Value:"dvportgroup-2189"},
                Name:       "NJO",
                Accessible: true,
                IpPoolName: "NJO",
                IpPoolId:   1,
            },
        },
        {
            Name: "tag",
            Op:   "assign",
            Val:  types.ArrayOfTag{},
        },
        {
            Name: "triggeredAlarmState",
            Op:   "assign",
            Val:  types.ArrayOfAlarmState{},
        },
        {
            Name: "value",
            Op:   "assign",
            Val:  types.ArrayOfCustomFieldValue{},
        },
        {
            Name: "vm",
            Op:   "assign",
            Val:  types.ArrayOfManagedObjectReference{
                ManagedObjectReference: []types.ManagedObjectReference{
                    {Type:"VirtualMachine", Value:"vm-5951"},
                    {Type:"VirtualMachine", Value:"vm-5892"},
                    {Type:"VirtualMachine", Value:"vm-5657"},
                    {Type:"VirtualMachine", Value:"vm-5640"},
                    {Type:"VirtualMachine", Value:"vm-5573"},
                    {Type:"VirtualMachine", Value:"vm-5891"},
                    {Type:"VirtualMachine", Value:"vm-5574"},
                    {Type:"VirtualMachine", Value:"vm-5572"},
                    {Type:"VirtualMachine", Value:"vm-5560"},
                    {Type:"VirtualMachine", Value:"vm-5639"},
                    {Type:"VirtualMachine", Value:"vm-5481"},
                    {Type:"VirtualMachine", Value:"vm-5641"},
                    {Type:"VirtualMachine", Value:"vm-5469"},
                    {Type:"VirtualMachine", Value:"vm-5465"},
                    {Type:"VirtualMachine", Value:"vm-5284"},
                    {Type:"VirtualMachine", Value:"vm-5257"},
                    {Type:"VirtualMachine", Value:"vm-5256"},
                    {Type:"VirtualMachine", Value:"vm-5255"},
                    {Type:"VirtualMachine", Value:"vm-5254"},
                    {Type:"VirtualMachine", Value:"vm-5236"},
                    {Type:"VirtualMachine", Value:"vm-5557"},
                    {Type:"VirtualMachine", Value:"vm-5115"},
                    {Type:"VirtualMachine", Value:"vm-5114"},
                    {Type:"VirtualMachine", Value:"vm-5113"},
                    {Type:"VirtualMachine", Value:"vm-5074"},
                    {Type:"VirtualMachine", Value:"vm-5073"},
                    {Type:"VirtualMachine", Value:"vm-5071"},
                    {Type:"VirtualMachine", Value:"vm-5053"},
                    {Type:"VirtualMachine", Value:"vm-5052"},
                    {Type:"VirtualMachine", Value:"vm-4149"},
                    {Type:"VirtualMachine", Value:"vm-4137"},
                    {Type:"VirtualMachine", Value:"vm-5479"},
                    {Type:"VirtualMachine", Value:"vm-5285"},
                    {Type:"VirtualMachine", Value:"vm-3666"},
                    {Type:"VirtualMachine", Value:"vm-3647"},
                    {Type:"VirtualMachine", Value:"vm-2869"},
                    {Type:"VirtualMachine", Value:"vm-2839"},
                    {Type:"VirtualMachine", Value:"vm-6132"},
                    {Type:"VirtualMachine", Value:"vm-2722"},
                    {Type:"VirtualMachine", Value:"vm-5051"},
                    {Type:"VirtualMachine", Value:"vm-2687"},
                    {Type:"VirtualMachine", Value:"vm-1199"},
                    {Type:"VirtualMachine", Value:"vm-6040"},
                    {Type:"VirtualMachine", Value:"vm-5684"},
                    {Type:"VirtualMachine", Value:"vm-1076"},
                    {Type:"VirtualMachine", Value:"vm-4969"},
                    {Type:"VirtualMachine", Value:"vm-2912"},
                    {Type:"VirtualMachine", Value:"vm-1047"},
                    {Type:"VirtualMachine", Value:"vm-1314"},
                    {Type:"VirtualMachine", Value:"vm-1940"},
                    {Type:"VirtualMachine", Value:"vm-997"},
                    {Type:"VirtualMachine", Value:"vm-5050"},
                    {Type:"VirtualMachine", Value:"vm-1784"},
                    {Type:"VirtualMachine", Value:"vm-996"},
                    {Type:"VirtualMachine", Value:"vm-995"},
                    {Type:"VirtualMachine", Value:"vm-1530"},
                    {Type:"VirtualMachine", Value:"vm-2651"},
                    {Type:"VirtualMachine", Value:"vm-936"},
                    {Type:"VirtualMachine", Value:"vm-373"},
                    {Type:"VirtualMachine", Value:"vm-916"},
                    {Type:"VirtualMachine", Value:"vm-784"},
                    {Type:"VirtualMachine", Value:"vm-5300"},
                    {Type:"VirtualMachine", Value:"vm-783"},
                    {Type:"VirtualMachine", Value:"vm-1203"},
                    {Type:"VirtualMachine", Value:"vm-992"},
                    {Type:"VirtualMachine", Value:"vm-1223"},
                    {Type:"VirtualMachine", Value:"vm-1514"},
                    {Type:"VirtualMachine", Value:"vm-1075"},
                    {Type:"VirtualMachine", Value:"vm-5917"},
                    {Type:"VirtualMachine", Value:"vm-106"},
                    {Type:"VirtualMachine", Value:"vm-134"},
                    {Type:"VirtualMachine", Value:"vm-651"},
                    {Type:"VirtualMachine", Value:"vm-5893"},
                    {Type:"VirtualMachine", Value:"vm-1322"},
                    {Type:"VirtualMachine", Value:"vm-1522"},
                    {Type:"VirtualMachine", Value:"vm-2911"},
                    {Type:"VirtualMachine", Value:"vm-2577"},
                    {Type:"VirtualMachine", Value:"vm-107"},
                    {Type:"VirtualMachine", Value:"vm-4756"},
                    {Type:"VirtualMachine", Value:"vm-161"},
                    {Type:"VirtualMachine", Value:"vm-1556"},
                    {Type:"VirtualMachine", Value:"vm-1295"},
                    {Type:"VirtualMachine", Value:"vm-1115"},
                    {Type:"VirtualMachine", Value:"vm-99"},
                    {Type:"VirtualMachine", Value:"vm-2024"},
                    {Type:"VirtualMachine", Value:"vm-395"},
                    {Type:"VirtualMachine", Value:"vm-133"},
                    {Type:"VirtualMachine", Value:"vm-90"},
                    {Type:"VirtualMachine", Value:"vm-2456"},
                    {Type:"VirtualMachine", Value:"vm-113"},
                    {Type:"VirtualMachine", Value:"vm-5075"},
                    {Type:"VirtualMachine", Value:"vm-486"},
                    {Type:"VirtualMachine", Value:"vm-935"},
                    {Type:"VirtualMachine", Value:"vm-765"},
                    {Type:"VirtualMachine", Value:"vm-650"},
                    {Type:"VirtualMachine", Value:"vm-1014"},
                    {Type:"VirtualMachine", Value:"vm-5070"},
                    {Type:"VirtualMachine", Value:"vm-2026"},
                    {Type:"VirtualMachine", Value:"vm-1539"},
                    {Type:"VirtualMachine", Value:"vm-128"},
                    {Type:"VirtualMachine", Value:"vm-1512"},
                    {Type:"VirtualMachine", Value:"vm-991"},
                    {Type:"VirtualMachine", Value:"vm-117"},
                    {Type:"VirtualMachine", Value:"vm-109"},
                    {Type:"VirtualMachine", Value:"vm-1470"},
                    {Type:"VirtualMachine", Value:"vm-5571"},
                    {Type:"VirtualMachine", Value:"vm-2859"},
                    {Type:"VirtualMachine", Value:"vm-1140"},
                    {Type:"VirtualMachine", Value:"vm-2578"},
                    {Type:"VirtualMachine", Value:"vm-1237"},
                    {Type:"VirtualMachine", Value:"vm-1054"},
                    {Type:"VirtualMachine", Value:"vm-1297"},
                    {Type:"VirtualMachine", Value:"vm-1305"},
                    {Type:"VirtualMachine", Value:"vm-2751"},
                    {Type:"VirtualMachine", Value:"vm-102"},
                    {Type:"VirtualMachine", Value:"vm-1490"},
                    {Type:"VirtualMachine", Value:"vm-3668"},
                    {Type:"VirtualMachine", Value:"vm-382"},
                    {Type:"VirtualMachine", Value:"vm-1489"},
                    {Type:"VirtualMachine", Value:"vm-1500"},
                    {Type:"VirtualMachine", Value:"vm-2952"},
                    {Type:"VirtualMachine", Value:"vm-2116"},
                    {Type:"VirtualMachine", Value:"vm-993"},
                    {Type:"VirtualMachine", Value:"vm-1501"},
                    {Type:"VirtualMachine", Value:"vm-575"},
                    {Type:"VirtualMachine", Value:"vm-5389"},
                    {Type:"VirtualMachine", Value:"vm-1513"},
                    {Type:"VirtualMachine", Value:"vm-1523"},
                    {Type:"VirtualMachine", Value:"vm-1524"},
                    {Type:"VirtualMachine", Value:"vm-1529"},
                    {Type:"VirtualMachine", Value:"vm-2603"},
                    {Type:"VirtualMachine", Value:"vm-1783"},
                    {Type:"VirtualMachine", Value:"vm-1517"},
                    {Type:"VirtualMachine", Value:"vm-2115"},
                    {Type:"VirtualMachine", Value:"vm-315"},
                    {Type:"VirtualMachine", Value:"vm-2350"},
                    {Type:"VirtualMachine", Value:"vm-5072"},
                    {Type:"VirtualMachine", Value:"vm-1296"},
                    {Type:"VirtualMachine", Value:"vm-2488"},
                    {Type:"VirtualMachine", Value:"vm-5467"},
                    {Type:"VirtualMachine", Value:"vm-2512"},
                    {Type:"VirtualMachine", Value:"vm-2541"},
                    {Type:"VirtualMachine", Value:"vm-2574"},
                    {Type:"VirtualMachine", Value:"vm-2576"},
                    {Type:"VirtualMachine", Value:"vm-1108"},
                    {Type:"VirtualMachine", Value:"vm-2625"},
                    {Type:"VirtualMachine", Value:"vm-5559"},
                    {Type:"VirtualMachine", Value:"vm-2653"},
                },
            },
        },
    },
    MissingSet: nil,
}

```

**Comment by perfecto25** [comment]
Found the issue, one of the vCenter network objects did not have proper permissions, I re-applied the Role for the user I'm using to create the vm, and propagaded down to all children, re-ran vm.create again and its working.

any way to have govc do an exception checks for permission-type errors? The nil error it spits out is not helpful.  Thanks.

**Comment by dougm** [comment]
Yes, at the very least we can avoid the panic.
