### ISSUE TITLE
Panic sorting events

### ISSUE THREAD

**Issue by tenczar** [vmware/govmomi#1055]
I received this error while processing vcenter events.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab4652]

goroutine 39 [running]:
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.baseEvent.Less(0xc420222700, 0xa, 0x10, 0x9, 0x3, 0x1)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/sort.go:40 +0x42
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*baseEvent).Less(0xc42033bd00, 0x9, 0x3, 0x1535901)
	<autogenerated>:1 +0x62
sort.quickSort(0x14f8140, 0xc42033bd00, 0x0, 0xa, 0x8)
	/usr/local/Cellar/go/1.9/libexec/src/sort/sort.go:207 +0x1b2
sort.Sort(0x14f8140, 0xc42033bd00)
	/usr/local/Cellar/go/1.9/libexec/src/sort/sort.go:220 +0x79
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.Sort(0xc420222700, 0xa, 0x10)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/sort.go:30 +0x6d
github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter.(*vCenterDriver).handler.func1(0xc420204c90, 0x6, 0xc420204cb0, 0x8, 0xc420222700, 0xa, 0x10, 0x0, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter/vcenter.go:104 +0xad
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*eventProcessor).process(0xc4203cbe70, 0xc420211ce0, 0x15, 0xc420218840, 0x51, 0xc420311e00, 0x1, 0x4, 0xa81b49, 0xc4202ec580)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/processor.go:137 +0x1c2
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*eventProcessor).run.func1(0xc420311e00, 0x1, 0x4, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/processor.go:93 +0x88
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property.Wait.func1(0xc4202d6180, 0x1, 0x4, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property/wait.go:59 +0xd6
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property.WaitForUpdates(0x14f8780, 0xc42000fe80, 0xc420347b00, 0xc420347950, 0xc4203cb940, 0x0, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property/wait.go:110 +0x201
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property.Wait(0x14f8780, 0xc42000fe80, 0xc420347b00, 0xc420211ce0, 0x15, 0xc420218840, 0x51, 0xc420045eb0, 0x1, 0x1, ...)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/property/wait.go:57 +0x13a
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*eventProcessor).run(0xc420347e70, 0x14f8780, 0xc42000fe80, 0xc420204c01, 0x0, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/processor.go:92 +0x9fd
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.Manager.Events(0x0, 0x0, 0xc4202ec580, 0xc420205220, 0xc, 0xc420205250, 0xc, 0xc4201e6150, 0xc42001ad80, 0xa, ...)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/manager.go:183 +0x1d4
github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter.(*vCenterDriver).Consume.func1(0xc4201e6180, 0x14f8780, 0xc42000fe80, 0xc42005aba0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter/vcenter.go:69 +0x16c
created by github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter.(*vCenterDriver).Consume
	/Users/ntenczar/go/src/github.com/vmware/dispatch/pkg/event-driver/drivers/vcenter/vcenter.go:67 +0x126
```
I received this error while running 0.17.0. Using 0.17.0 resolved a separate error that I was getting using 0.16.0. Here is a small snapshot of that event.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab44a8]

goroutine 13 [running]:
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*eventTailer).newEvents(0xc4202fcdfc, 0xc4200ea000, 0xa, 0x10, 0x0, 0x0, 0x0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/processor.go:164 +0x68
github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event.(*eventProcessor).process(0xc4202e3e70, 0xc4201e2ac0, 0x15, 0xc4202c6600, 0x51, 0xc42015f980, 0x1, 0x4, 0xa81b49, 0xc42007cdc0)
	/Users/ntenczar/go/src/github.com/vmware/dispatch/vendor/github.com/vmware/govmomi/event/processor.go:132 +0x17b
```
Again, this second error seems to have been resolved by using 0.17.0

The particular vcenter environment may be unique because it is using an external PSC and VSAN.

**Comment by dougm** [comment]
@tenczar what revision of govmomi do you have vendored?  I spoke with @kars7e about this yesterday:

The likely issue that was recently fixed: https://github.com/vmware/govmomi/blob/master/vim25/types/helpers.go#L92-L94

The other work around is to set the vim namespace to 6.0, by setting soap.Client.Version like so: https://github.com/vmware/vic/blob/master/pkg/vsphere/session/session.go#L217

You can also filter by event type, which would avoid the host system events and others you don't care about.  Example in VIC: https://github.com/vmware/vic/blob/1912c1709a96c098516f45af15fb29acf58553a3/lib/portlayer/event/collector/vsphere/collector.go#L111-L130

then pass to Events(), the filter param was also added somewhat recently.

**Comment by tenczar** [comment]
Originally, I was using 0.16.0 and was getting a different error. I updated to 0.17.0 and found that I hit the error in the first block above.

**Comment by dougm** [comment]
ok, have you tried either of the workarounds?

I can also take a look if I can access your VC environment to see why this would still happen with 0.17

**Comment by dougm** [comment]
To try the version workaround:
```diff
modified   pkg/event-driver/drivers/vcenter/vcenter.go
@@ -174,7 +174,11 @@ func newVCenterClient(ctx context.Context, vcenterURL string, insecure bool) (*g
 		return nil, err
 	}
 
-	return govmomi.NewClient(ctx, url, insecure)
+	c, err := govmomi.NewClient(ctx, url, insecure)
+	if err == nil {
+		c.Version = "6.0"
+	}
+	return c, err
 }
 
 func convertToTopic(eventType string) string {
```

**Comment by dougm** [comment]
@tenczar still having this issue?

**Comment by dougm** [comment]
I wasn't able to reproduce this against the same vCenter env, please re-open if still an issue.
