### ISSUE TITLE
Panic in govc dvs.portgroup.info on version 0.16.0 and 0.17.0 but not seen in 0.15.0

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/govmomi#1060]
Command still actually returns expected results but panics at the end:
0.16.0
```
panic: interface conversion: types.BaseVmwareDistributedVirtualSwitchVlanSpec is *types.VmwareDistributedVirtualSwitchTrunkVlanSpec, not *types.VmwareDistributedVirtualSwitchVlanIdSpec

goroutine 1 [running]:
github.com/vmware/govmomi/govc/dvs/portgroup.(*info).Run(0xc420077110, 0x18ad580, 0xc42007e010, 0xc4200944e0, 0x0, 0x0)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/dvs/portgroup/info.go:144 +0xc16
github.com/vmware/govmomi/govc/cli.Run(0xc420088050, 0x3, 0x3, 0xc88700)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/cli/command.go:156 +0x522
main.main()
	/home/vmware/release/src/github.com/vmware/govmomi/govc/main.go:82 +0x63
```

0.17.0
```
panic: interface conversion: types.BaseVmwareDistributedVirtualSwitchVlanSpec is *types.VmwareDistributedVirtualSwitchTrunkVlanSpec, not *types.VmwareDistributedVirtualSwitchVlanIdSpec

goroutine 1 [running]:
github.com/vmware/govmomi/govc/dvs/portgroup.(*info).Run(0xc4200a3200, 0x110f8c0, 0xc420036058, 0xc4200805a0, 0x0, 0x0)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/dvs/portgroup/info.go:144 +0xb71
github.com/vmware/govmomi/govc/cli.Run(0xc4200300d0, 0x3, 0x3, 0xc420098058)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/cli/command.go:156 +0x53b
main.main()
	/home/vmware/release/src/github.com/vmware/govmomi/govc/main.go:85 +0x63
```

**Comment by dougm** [comment]
Don't think this code has changed since it was added (#471) , but I will look into it.
