### ISSUE TITLE
vcsim: unable to connect when using PowerCLI 10 GA

### ISSUE THREAD

**Issue by kars7e** [vmware/govmomi#1063]
vcsim version: https://github.com/vmware/govmomi/commit/8872366d5b156a8cbef4b7291cd6e9026b8129a5
PowerCLI version: 10.0.0.7895300 GA
PowerShell version v6.0.1 GA

Running following sequence:
```bash
docker run --rm -it --net=host  vmware/dispatch-powershell-base:0.0.2
Set-PowerCLIConfiguration -InvalidCertificateAction ignore -confirm:$false
Connect-VIServer -Server 127.0.0.1 -Port 8989 -User user -Password pass
```
Gives:
```
Connect-VIServer : An error occurred while sending the request.
At line:1 char:1
+ Connect-VIServer -Server 127.0.0.1 -Port 8989 -User user -Password pa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-VIServer], CommunicationException
+ FullyQualifiedErrorId : System.ServiceModel.CommunicationException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer
```

Here is the trace from vcsim:
```
$ vcsim -trace
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=4515
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><RetrieveServiceContent xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><RetrieveServiceContentResponse xmlns="urn:vim25"><returnval><rootFolder type="Folder">group-d1</rootFolder><propertyCollector type="PropertyCollector">propertyCollector</propertyCollector><viewManager type="ViewManager">ViewManager</viewManager><about><name>VMware vCenter Server (govmomi simulator)</name><fullName>VMware vCenter Server 6.5.0 build-5973321</fullName><vendor>VMware, Inc.</vendor><version>6.5.0</version><build>5973321</build><localeVersion>INTL</localeVersion><localeBuild>000</localeBuild><osType>linux-amd64</osType><productLineId>vpx</productLineId><apiType>VirtualCenter</apiType><apiVersion>6.5</apiVersion><instanceUuid>dbed6e0c-bd88-4ef6-b594-21283e1c677f</instanceUuid><licenseProductName>VMware VirtualCenter Server</licenseProductName><licenseProductVersion>6.0</licenseProductVersion></about><setting type="OptionManager">VpxSettings</setting><userDirectory type="UserDirectory">UserDirectory</userDirectory><sessionManager type="SessionManager">SessionManager</sessionManager><authorizationManager type="AuthorizationManager">AuthorizationManager</authorizationManager><serviceManager type="ServiceManager">ServiceMgr</serviceManager><perfManager type="PerformanceManager">PerfMgr</perfManager><scheduledTaskManager type="ScheduledTaskManager">ScheduledTaskManager</scheduledTaskManager><alarmManager type="AlarmManager">AlarmManager</alarmManager><eventManager type="EventManager">EventManager</eventManager><taskManager type="TaskManager">TaskManager</taskManager><extensionManager type="ExtensionManager">ExtensionManager</extensionManager><customizationSpecManager type="CustomizationSpecManager">CustomizationSpecManager</customizationSpecManager><customFieldsManager type="CustomFieldsManager">CustomFieldsManager</customFieldsManager><diagnosticManager type="DiagnosticManager">DiagMgr</diagnosticManager><licenseManager type="LicenseManager">LicenseManager</licenseManager><searchIndex type="SearchIndex">SearchIndex</searchIndex><fileManager type="FileManager">FileManager</fileManager><datastoreNamespaceManager type="DatastoreNamespaceManager">DatastoreNamespaceManager</datastoreNamespaceManager><virtualDiskManager type="VirtualDiskManager">virtualDiskManager</virtualDiskManager><snmpSystem type="HostSnmpSystem">SnmpSystem</snmpSystem><vmProvisioningChecker type="VirtualMachineProvisioningChecker">ProvChecker</vmProvisioningChecker><vmCompatibilityChecker type="VirtualMachineCompatibilityChecker">CompatChecker</vmCompatibilityChecker><ovfManager type="OvfManager">OvfManager</ovfManager><ipPoolManager type="IpPoolManager">IpPoolManager</ipPoolManager><dvSwitchManager type="DistributedVirtualSwitchManager">DVSManager</dvSwitchManager><hostProfileManager type="HostProfileManager">HostProfileManager</hostProfileManager><clusterProfileManager type="ClusterProfileManager">ClusterProfileManager</clusterProfileManager><complianceManager type="ProfileComplianceManager">MoComplianceManager</complianceManager><localizationManager type="LocalizationManager">LocalizationManager</localizationManager><storageResourceManager type="StorageResourceManager">StorageResourceManager</storageResourceManager><guestOperationsManager type="GuestOperationsManager">guestOperationsManager</guestOperationsManager><overheadMemoryManager type="OverheadMemoryManager">OverheadMemoryManager</overheadMemoryManager><certificateManager type="CertificateManager">certificateManager</certificateManager><ioFilterManager type="IoFilterManager">IoFilterManager</ioFilterManager><vStorageObjectManager type="VcenterVStorageObjectManager">VStorageObjectManager</vStorageObjectManager><hostSpecManager type="HostSpecificationManager">HostSpecificationManager</hostSpecManager><cryptoManager type="CryptoManagerKmip">CryptoManager</cryptoManager><healthUpdateManager type="HealthUpdateManager">HealthUpdateManager</healthUpdateManager><failoverClusterConfigurator type="FailoverClusterConfigurator">FailoverClusterConfigurator</failoverClusterConfigurator><failoverClusterManager type="FailoverClusterManager">FailoverClusterManager</failoverClusterManager></returnval></RetrieveServiceContentResponse></soapenv:Body></soapenv:Envelope>
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Login xmlns="urn:vim25"><_this type="SessionManager">SessionManager</_this><userName>user</userName><password>pass</password></Login></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><LoginResponse xmlns="urn:vim25"><returnval><key>9623b9a1-1dc6-410c-986e-016f917820d7</key><userName>user</userName><fullName>user</fullName><loginTime>2018-03-12T16:06:22.619383428-07:00</loginTime><lastActiveTime>2018-03-12T16:06:22.619383823-07:00</lastActiveTime><locale>en_US</locale><messageLocale>en_US</messageLocale></returnval></LoginResponse></soapenv:Body></soapenv:Envelope>
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><QueryOptions xmlns="urn:vim25"><_this type="OptionManager">VpxSettings</_this><name>config.vpxd.sso.sts.uri</name></QueryOptions></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><QueryOptionsResponse xmlns="urn:vim25"><returnval xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="OptionValue"><key>config.vpxd.sso.sts.uri</key><value XMLSchema-instance:type="xsd:string">https://127.0.0.1/sts/STSService/vsphere.local</value></returnval></QueryOptionsResponse></soapenv:Body></soapenv:Envelope>
```

**Comment by dougm** [comment]
@kars7e you mentioned in slack, when starting vcsim on port 443, you get the error:
`connect-viserver : There was no endpoint listening at https://127.0.0.1/lookupservice/sdk that could accept the message.`

I glanced at the powercli source and it looks like 443 is hardcoded in this case, rather than using the `-Port` flag.  I haven't come across the `/lookupservice/sdk` before, vcsim does not have support for it.

I wonder if the PowerCLI folks could help here, maybe there's a setting to avoid hitting `/lookupservice/sdk`.  And/or someone could point us at how this API endpoint is used so we can consider adding vcsim support.  cc @lamw @jakerobinson

**Comment by jakerobinson** [comment]
@kamennikolov Is there a way a user can bypass the Lookup Service?

**Comment by atanasa** [comment]
I don't think it should be failing to connect if the Lookup Service is not there. If the Lookup Service is missing some functionality would not work (e.g. tags) if you try to use those.

Can you extract a stack trace from the error:
```powershell
    $lastError = $Error[0]
    $lastError
    $lastError.Exception
    $lastError.Exception.StackTrace
    $lastError.Exception.InnerException
    $lastError.Exception.InnerException.StackTrace
    $lastError.Exception.InnerException.InnerException
    $lastError.Exception.InnerException.InnerException.StackTrace
```

**Comment by kars7e** [comment]
@atanasa 

```powershell
PS /Users/kstepniewski> connect-viserver -server "10.1.137.24"  -User "user" -Password "pass"                                                                                                                                                                                                                                                                               
connect-viserver : There was no endpoint listening at https://127.0.0.1/lookupservice/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
At line:1 char:1
+ connect-viserver -server "10.1.137.24"  -User "user" -Password "pass"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-VIServer], EndpointNotFoundException
+ FullyQualifiedErrorId : System.ServiceModel.EndpointNotFoundException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer

PS /Users/kstepniewski>     $lastError = $Error[0]
PS /Users/kstepniewski>     $lastError
connect-viserver : There was no endpoint listening at https://127.0.0.1/lookupservice/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
At line:1 char:1
+ connect-viserver -server "10.1.137.24"  -User "user" -Password "pass"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-VIServer], EndpointNotFoundException
+ FullyQualifiedErrorId : System.ServiceModel.EndpointNotFoundException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer

PS /Users/kstepniewski>     $lastError.Exception
There was no endpoint listening at https://127.0.0.1/lookupservice/sdk that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
PS /Users/kstepniewski>     $lastError.Exception.StackTrace
   at VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer.HandleConnectError(List`1 connectExceptions)
   at VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer.ProcessRecordErrorHandled()
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ErrorCallbackCmdletBase.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS /Users/kstepniewski>     $lastError.Exception.InnerException
PS /Users/kstepniewski>     $lastError.Exception.InnerException.StackTrace
PS /Users/kstepniewski>     $lastError.Exception.InnerException.InnerException
PS /Users/kstepniewski>     $lastError.Exception.InnerException.InnerException.StackTrace
```

trace from vcsim:
```
$ sudo vcsim -httptest.serve 0.0.0.0:443 -trace
export GOVC_URL=https://user:pass@[::]:443/sdk GOVC_SIM_PID=51564
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><RetrieveServiceContent xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></RetrieveServiceContent></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><RetrieveServiceContentResponse xmlns="urn:vim25"><returnval><rootFolder type="Folder">group-d1</rootFolder><propertyCollector type="PropertyCollector">propertyCollector</propertyCollector><viewManager type="ViewManager">ViewManager</viewManager><about><name>VMware vCenter Server (govmomi simulator)</name><fullName>VMware vCenter Server 6.5.0 build-5973321</fullName><vendor>VMware, Inc.</vendor><version>6.5.0</version><build>5973321</build><localeVersion>INTL</localeVersion><localeBuild>000</localeBuild><osType>darwin-amd64</osType><productLineId>vpx</productLineId><apiType>VirtualCenter</apiType><apiVersion>6.5</apiVersion><instanceUuid>dbed6e0c-bd88-4ef6-b594-21283e1c677f</instanceUuid><licenseProductName>VMware VirtualCenter Server</licenseProductName><licenseProductVersion>6.0</licenseProductVersion></about><setting type="OptionManager">VpxSettings</setting><userDirectory type="UserDirectory">UserDirectory</userDirectory><sessionManager type="SessionManager">SessionManager</sessionManager><authorizationManager type="AuthorizationManager">AuthorizationManager</authorizationManager><serviceManager type="ServiceManager">ServiceMgr</serviceManager><perfManager type="PerformanceManager">PerfMgr</perfManager><scheduledTaskManager type="ScheduledTaskManager">ScheduledTaskManager</scheduledTaskManager><alarmManager type="AlarmManager">AlarmManager</alarmManager><eventManager type="EventManager">EventManager</eventManager><taskManager type="TaskManager">TaskManager</taskManager><extensionManager type="ExtensionManager">ExtensionManager</extensionManager><customizationSpecManager type="CustomizationSpecManager">CustomizationSpecManager</customizationSpecManager><customFieldsManager type="CustomFieldsManager">CustomFieldsManager</customFieldsManager><diagnosticManager type="DiagnosticManager">DiagMgr</diagnosticManager><licenseManager type="LicenseManager">LicenseManager</licenseManager><searchIndex type="SearchIndex">SearchIndex</searchIndex><fileManager type="FileManager">FileManager</fileManager><datastoreNamespaceManager type="DatastoreNamespaceManager">DatastoreNamespaceManager</datastoreNamespaceManager><virtualDiskManager type="VirtualDiskManager">virtualDiskManager</virtualDiskManager><snmpSystem type="HostSnmpSystem">SnmpSystem</snmpSystem><vmProvisioningChecker type="VirtualMachineProvisioningChecker">ProvChecker</vmProvisioningChecker><vmCompatibilityChecker type="VirtualMachineCompatibilityChecker">CompatChecker</vmCompatibilityChecker><ovfManager type="OvfManager">OvfManager</ovfManager><ipPoolManager type="IpPoolManager">IpPoolManager</ipPoolManager><dvSwitchManager type="DistributedVirtualSwitchManager">DVSManager</dvSwitchManager><hostProfileManager type="HostProfileManager">HostProfileManager</hostProfileManager><clusterProfileManager type="ClusterProfileManager">ClusterProfileManager</clusterProfileManager><complianceManager type="ProfileComplianceManager">MoComplianceManager</complianceManager><localizationManager type="LocalizationManager">LocalizationManager</localizationManager><storageResourceManager type="StorageResourceManager">StorageResourceManager</storageResourceManager><guestOperationsManager type="GuestOperationsManager">guestOperationsManager</guestOperationsManager><overheadMemoryManager type="OverheadMemoryManager">OverheadMemoryManager</overheadMemoryManager><certificateManager type="CertificateManager">certificateManager</certificateManager><ioFilterManager type="IoFilterManager">IoFilterManager</ioFilterManager><vStorageObjectManager type="VcenterVStorageObjectManager">VStorageObjectManager</vStorageObjectManager><hostSpecManager type="HostSpecificationManager">HostSpecificationManager</hostSpecManager><cryptoManager type="CryptoManagerKmip">CryptoManager</cryptoManager><healthUpdateManager type="HealthUpdateManager">HealthUpdateManager</healthUpdateManager><failoverClusterConfigurator type="FailoverClusterConfigurator">FailoverClusterConfigurator</failoverClusterConfigurator><failoverClusterManager type="FailoverClusterManager">FailoverClusterManager</failoverClusterManager></returnval></RetrieveServiceContentResponse></soapenv:Body></soapenv:Envelope>
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Login xmlns="urn:vim25"><_this type="SessionManager">SessionManager</_this><userName>user</userName><password>pass</password></Login></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><LoginResponse xmlns="urn:vim25"><returnval><key>c33b8f67-dec3-4cfe-b713-ffb5f3819685</key><userName>user</userName><fullName>user</fullName><loginTime>2018-03-13T15:53:34.896921964-07:00</loginTime><lastActiveTime>2018-03-13T15:53:34.896922065-07:00</lastActiveTime><locale>en_US</locale><messageLocale>en_US</messageLocale></returnval></LoginResponse></soapenv:Body></soapenv:Envelope>
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><QueryOptions xmlns="urn:vim25"><_this type="OptionManager">VpxSettings</_this><name>config.vpxd.sso.sts.uri</name></QueryOptions></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><QueryOptionsResponse xmlns="urn:vim25"><returnval xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="OptionValue"><key>config.vpxd.sso.sts.uri</key><value XMLSchema-instance:type="xsd:string">https://127.0.0.1/sts/STSService/vsphere.local</value></returnval></QueryOptionsResponse></soapenv:Body></soapenv:Envelope>
Request: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><CurrentTime xmlns="urn:vim25"><_this type="ServiceInstance">ServiceInstance</_this></CurrentTime></s:Body></s:Envelope>
Response: <?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><CurrentTimeResponse xmlns="urn:vim25"><returnval>2018-03-13T15:54:34.938967292-07:00</returnval></CurrentTimeResponse></soapenv:Body></soapenv:Envelope>
```

I also checked what happens if I listen on default `127.0.0.1:8989` for vcsim:
```
PS /Users/kstepniewski> connect-viserver -server "127.0.0.1" -Port 8989  -User "user" -Password "pass"                                                                                                                                                                                                                                                                      connect-viserver : An error occurred while sending the request.                                                                                                                                                                                                                                                                                                             At line:1 char:1                                                                                                                                                                                                                                                                                                                                                            + connect-viserver -server "127.0.0.1" -Port 8989  -User "user" -Passwo ...                                                                                                                                                                                                                                                                                                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                     + CategoryInfo          : NotSpecified: (:) [Connect-VIServer], CommunicationException                                                                                                                                                                                                                                                                                      + FullyQualifiedErrorId : System.ServiceModel.CommunicationException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer

PS /Users/kstepniewski>     $lastError = $Error[0]
PS /Users/kstepniewski>     $lastError
connect-viserver : An error occurred while sending the request.
At line:1 char:1
+ connect-viserver -server "127.0.0.1" -Port 8989  -User "user" -Passwo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-VIServer], CommunicationException
+ FullyQualifiedErrorId : System.ServiceModel.CommunicationException,VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer

PS /Users/kstepniewski>     $lastError.Exception
An error occurred while sending the request.
PS /Users/kstepniewski>     $lastError.Exception.StackTrace
   at VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer.HandleConnectError(List`1 connectExceptions)
   at VMware.VimAutomation.ViCore.Cmdlets.Commands.ConnectVIServer.ProcessRecordErrorHandled()
   at VMware.VimAutomation.Sdk.Util10Ps.BaseCmdlet.ErrorCallbackCmdletBase.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS /Users/kstepniewski>     $lastError.Exception.InnerException
An error occurred while sending the request.
PS /Users/kstepniewski>     $lastError.Exception.InnerException.StackTrace
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.ServiceModelHttpMessageHandler.<SendAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.<SendRequestAsync>d__13.MoveNext()
PS /Users/kstepniewski>     $lastError.Exception.InnerException.InnerException
Couldn't connect to server
PS /Users/kstepniewski>     $lastError.Exception.InnerException.InnerException.StackTrace
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
```

**Comment by jakerobinson** [comment]
Thanks for jumping in on this @atanasa! I would love to see PowerCLI connect to vCenter Simulator, especially if we can run all of it in a container. This could have some implications on our testing.

@dougm - Is VIC or anyone else using this in any serious integration testing?

**Comment by jakerobinson** [comment]
@dougm one reason we might consider implementing Lookup Service into the simulator is connecting multiple vCenters. That's one of the reasons that PowerCLI uses it. You can do:
```
Connect-ViServer <my_vc> --allLinked
```
and it will authenticate to multiple vCs (or maybe even multiple simulators)

**Comment by dougm** [comment]
@jakerobinson yes, VIC, Kubernetes (vSphere Cloud Provider), Ansible (Python) and some others that aren't OSS.

Older versions of PowerCLI did work against vcsim, at least connect, Get-VM and a few other commands.  Any pointers to doc on the Lookup Service API?

**Comment by lamw** [comment]
@dougm Check out **Option 3** in this blog post [here|https://www.virtuallyghetto.com/2015/04/vcenter-server-6-0-tidbits-part-3-finding-all-deployed-platform-services-controller.html] which shows you how to connect to Lookup Service API (you'll need the vCloud Automation SDK bindings to access LS)

**Comment by jakerobinson** [comment]
@dougm yeah, I'll let @atanasa determine if that's a bug (sounds like we don't want to fail if Lookup Service is not there), but in all recent versions (6.5.1+) I never got it to work (back when vcsim was part of the VIC repo).

**Comment by dougm** [comment]
@lamw perfect, thanks!

**Comment by dougm** [comment]
The lookup service can be avoided if you start in ESX mode: `vcsim -esx`
With that, `Connect-VIServer` and `Get-VM` work at least.

We can add lookup service support to vcsim, but need to do some refactoring to support multiple API endpoints with their own vmodl.  I've been planning to do this to support other endpoints, such as pbm, sts, etc.

**Comment by atanasa** [comment]
This looks like a bug. We would need ideally instructions on how to reproduce it internally.

**Comment by dougm** [comment]
@atanasa to reproduce, use the summary steps provided by @kars7e : 
```
docker run --rm -it --net=host  vmware/dispatch-powershell-base:0.0.2
Set-PowerCLIConfiguration -InvalidCertificateAction ignore -confirm:$false
Connect-VIServer -Server 127.0.0.1 -Port 8989 -User user -Password pass
``
It can also be reproduced by just running vcsim directly instead of docker run: https://github.com/vmware/govmomi/tree/master/vcsim

`Connect-VIServer` works fine when running `vcsim -esx` as PowerCLI does not try talking to the lookup service in that case.

I did get a Lookup Service Go client and simulator working over the weekend and will open a PR this week.  There is still the issue that PowerCLI will only attempt port 443 for the lookup service, ideally we could use a non-privileged port.

**Comment by atanasa** [comment]
Thanks, we would look into it. Currently there is no way to specify a custom port for LS. In general there is the issue that vCenter does not report in a clean way where the LS is.
