### ISSUE TITLE
datastore.disk.info crashes with "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by juliohm1978** [vmware/govmomi#1066]
Using the latest release: v0.17.0

Curiously, I am able to create disks

```
$ govc datastore.disk.create -size=1GB kubevols/test.vmdk
[15-03-18 16:46:11] Creating [HUS2_Pool1_06-Lab-k8s] kubevols/test.vmdk...OK
```

... but unbale to query for disk information.

```
$ govc datastore.disk.info kubevols/asdf.vmdk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9da348]

goroutine 1 [running]:
github.com/vmware/govmomi/object.VirtualDiskManager.QueryVirtualDiskInfo(0x0, 0x0, 0xc42019e840, 0xc420034f20, 0x12, 0xc420034f40, 0x12, 0x110f8c0, 0xc420036100, 0xc4203ae2d0, ...)
	/home/vmware/release/src/github.com/vmware/govmomi/object/virtual_disk_manager_internal.go:91 +0x208
github.com/vmware/govmomi/govc/datastore/disk.(*info).Run(0xc420070c40, 0x110f8c0, 0xc420036100, 0xc42008c5a0, 0x0, 0x0)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/datastore/disk/info.go:129 +0x316
github.com/vmware/govmomi/govc/cli.Run(0xc4200300a0, 0x2, 0x2, 0xc4200400b8)
	/home/vmware/release/src/github.com/vmware/govmomi/govc/cli/command.go:156 +0x53b
main.main()
	/home/vmware/release/src/github.com/vmware/govmomi/govc/main.go:85 +0x63

```

**Comment by dougm** [comment]
Can you provide the output of: `govc about`

**Comment by juliohm1978** [comment]
Sure.

```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.0.0
Build:        5318200
OS type:      win32-x64
API type:     VirtualCenter
API version:  6.0
Product ID:   vpx
UUID:         99ED5B5D-1397-4758-9521-E64BD1C191E5
```
