### ISSUE TITLE
when getHostSystemManagementIp  meet some problems in vcsim

### ISSUE THREAD

**Issue by Mr-moyu** [vmware/govmomi#1107]
like this...
```bash
java.lang.NoSuchFieldException: type
        at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:149) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:167) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.HostSystem.getConfig(HostSystem.java:57) ~[yavijava-6.0.04.jar:?]```

**Comment by dougm** [comment]
Need to reproduce this, can you run vcsim with the `-trace` flag and include the request output in this issue?

**Comment by Mr-moyu** [comment]
you mean this?
```xml
Request: <?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><RetrieveProperties xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this><specSet><propSet><type>HostSystem</type><all>false</all><pathSet>name</pathSet></propSet><objectSet><obj type="HostSystem">host-22</obj><skip>false</skip></objectSet></specSet></RetrieveProperties></soapenv:Body></soapenv:Envelope>

**Comment by Mr-moyu** [comment]
[trace.txt](https://github.com/vmware/govmomi/files/1957298/trace.txt)

**Comment by dougm** [comment]
Yes, and the response looks fine (below).  I don't know why yavijava has a problem with this response.

```xml
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <soapenv:Body>
  <RetrievePropertiesResponse xmlns="urn:vim25">
   <returnval>
    <obj type="HostSystem">host-22</obj>
    <propSet>
     <name>name</name>
     <val xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="xsd:string">DC0_C0_H0</val>
    </propSet>
   </returnval>
  </RetrievePropertiesResponse>
 </soapenv:Body>
</soapenv:Envelope>
```

**Comment by Mr-moyu** [comment]
how about this exception?
```bash
java.lang.NoSuchFieldException: type
        at java.lang.Class.getField(Class.java:1703) ~[?:1.8.0_102]
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:260) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:356) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:231) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:106) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:98) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:146) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:167) ~[yavijava-6.0.04.jar:?]
        at com.vmware.vim25.mo.HostSystem.getConfig(HostSystem.java:57) ~[yavijava-6.0.04.jar:?]

**Comment by Mr-moyu** [comment]
This is in vim simulator/esx/host_config_info.go:
![zffuex8x](https://user-images.githubusercontent.com/26504403/39501165-ce0b6a70-4deb-11e8-80a9-f3d812a98a99.png)
and this is in yavijava:
![zffvipko](https://user-images.githubusercontent.com/26504403/39501169-dc4362a0-4deb-11e8-9146-5ff28f5225ed.png)

**Comment by dougm** [comment]
I see, `IoFilterInfo.Type` was added in version 6.5, but yavijava must be 6.0 or older.  Even though `Type` is empty, the field is still marshaled.  We should properly implement vim versioning in vcsim.

But for now, we could just remove the `Type` field from host_config_info.go as you have done.  Would that work for you or are there other fields with the same issue?

**Comment by Mr-moyu** [comment]
Thx @dougm ,I think that will be very helpful.

**Comment by dougm** [comment]
@Mr-moyu could you provide some yavijava code that reproduces the issue(s)?

**Comment by Mr-moyu** [comment]
like this？
![](https://user-images.githubusercontent.com/26504403/39501169-dc4362a0-4deb-11e8-9146-5ff28f5225ed.png)

**Comment by dougm** [comment]
I meant code we can run, like a .java file with a main() method that uses yavijava.

**Comment by Mr-moyu** [comment]
https://github.com/yavijava/yavijava-samples      
Like method com.vmware.vim25.mo.HostSystem.getConfig(HostSystem).

**Comment by dougm** [comment]
You can use the new Record/Playback feature to solve this: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback
