### ISSUE TITLE
vcsim: VSAN system missing

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#1137]
Following code raises a traceback while running against vcsim server - 

Traceback 
```
# python vsan_cluster.py
Traceback (most recent call last):
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 635, in LookupWsdlType
    return GetWsdlType(ns, name)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 1032, in GetWsdlType
    typ = _LoadVmodlType(_wsdlDefMap[(ns, name)][0])
KeyError: ('', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 502, in ParseData
    parser.ParseFile(data)
  File "/private/tmp/python3-20171219-25486-1jmsr3a/Python-3.6.4/Modules/pyexpat.c", line 414, in StartElement
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 655, in StartElementHandler
    objType = self.LookupWsdlType(ns, name[:-5])
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 645, in LookupWsdlType
    return GuessWsdlType(name)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 1066, in GuessWsdlType
    raise UnknownWsdlTypeError(name)
pyVmomi.VmomiSupport.UnknownWsdlTypeError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vsan_cluster.py", line 42, in <module>
    status = config_mgr.QueryHostStatus()
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1357, in InvokeMethod
    raise exc
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1347, in InvokeMethod
    obj = deserializer.Deserialize(fd, info.result)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 833, in Deserialize
    ParseData(self.parser, response)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 513, in ParseData
    reraise(ParserError, pe, tb)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 502, in ParseData
    parser.ParseFile(data)
  File "/private/tmp/python3-20171219-25486-1jmsr3a/Python-3.6.4/Modules/pyexpat.c", line 414, in StartElement
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 655, in StartElementHandler
    objType = self.LookupWsdlType(ns, name[:-5])
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 645, in LookupWsdlType
    return GuessWsdlType(name)
  File "/Volumes/data/src/ansible/venvpy3/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 1066, in GuessWsdlType
    raise UnknownWsdlTypeError(name)
pyVmomi.SoapAdapter.ParserError: 'xml document: <http.client.HTTPResponse object at 0x107ec9dd8> parse error at: line:2, col:510'
```

Python reproducer - 

```python

from pyVim.connect import SmartConnect, Disconnect
import ssl
import atexit
from pyVmomi import vim

def connect():
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.verify_mode = ssl.CERT_NONE

    si = SmartConnect(host='0.0.0.0', user='user', pwd='pass', port=443, sslContext=context)
    atexit.register(Disconnect, si)
    content = si.RetrieveContent()
    return content

def get_obj(content, vimtype, name=None):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    if name is None:
        obj = []
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj.append(c)

    container.Destroy()
    return obj

content = connect()

esxi_name = 'DC0_H0'

host = get_obj(content, [vim.HostSystem], esxi_name)
config_mgr = host.configManager.vsanSystem
status = config_mgr.QueryHostStatus()

print(status)
```

vcsim traceback -

```
2018/05/20 22:24:56 managed object not found: HostVsanSystem:vsanSystem
```

**Comment by jtyr** [comment]
I'm getting the same error (also in [Ansible](https://github.com/ansible/ansible/pull/43435)) when querying `configManager.storageSystem.fileSystemVolumeInfo.mountInfo`. Does it means that `vcsim` is missing support for `storageSystem`?

**Comment by dougm** [comment]
vcsim doesn't populate this data by default current.  It is possible however, to use the Record+Playback feature to get this data in vcsim: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback
