### ISSUE TITLE
VCSIM: Clone VM Task is breaking

### ISSUE THREAD

**Issue by siddharth-kulshrestha** [vmware/govmomi#1896]
I am facing issues with VCSIM clone VM task.

It is resulting in nil pointer exception and returning End of File error due to that.

More context around the problem:
I have launched VCSIM server by using Record and Playback feature (with --load flag).
But Cloning VMs from few template VMs which were present already on vcenter is resulting in following error.

```Request:
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><CloneVM_Task xmlns="urn:vim25"><_this type="VirtualMachine">vm-266996</_this><folder type="Folder">group-v110344</folder><name>vm-0-200401-130251</name><spec><location><datastore type="Datastore">datastore-221689</datastore><pool type="ResourcePool">resgroup-110349</pool><host type="HostSystem">host-110373</host></location><template>false</template><config><name>vm-0-200401-130251</name><instanceUuid>968a2189-3445-4a97-9472-bb6ea3ab9ffe</instanceUuid><annotation>ABCSDFsa test annotation</annotation><numCPUs>2</numCPUs><numCoresPerSocket>1</numCoresPerSocket><memoryMB>4096</memoryMB><deviceChange xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="VirtualDeviceConfigSpec"><operation>remove</operation><device XMLSchema-instance:type="VirtualDisk"><key>2000</key><deviceInfo XMLSchema-instance:type="Description"><label>Hard disk 1</label><summary>52,428,800 KB</summary></deviceInfo><backing XMLSchema-instance:type="VirtualDiskFlatVer2BackingInfo"><fileName>[Test-Container] CENTOS_76/CENTOS_76.vmdk</fileName><datastore type="Datastore">datastore-110353</datastore><diskMode>persistent</diskMode><split>false</split><writeThrough>false</writeThrough><thinProvisioned>false</thinProvisioned><eagerlyScrub>true</eagerlyScrub><uuid>6000C293-40f6-470c-1ac1-ceac7c7d6808</uuid><contentId>ae115a52961efc1661e9ee41dbb76769</contentId><digestEnabled>false</digestEnabled><sharing>sharingNone</sharing></backing><controllerKey>1000</controllerKey><unitNumber>0</unitNumber><capacityInKB>52428800</capacityInKB><capacityInBytes>53687091200</capacityInBytes><shares><shares>1000</shares><level>normal</level></shares><storageIOAllocation><limit>-1</limit><shares><shares>1000</shares><level>normal</level></shares><reservation>0</reservation></storageIOAllocation><diskObjectId>146972-2000</diskObjectId></device></deviceChange></config><powerOn>false</powerOn></spec></CloneVM_Task></Body></Envelope>

2020/04/01 20:02:59 http: panic serving 192.146.154.247:32381: runtime error: invalid memory address or nil pointer dereference
goroutine 634 [running]:
net/http.(*conn).serve.func1(0xc000f4d9a0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xdc9b20, 0x1976640)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/vmware/govmomi/simulator.(*VirtualMachine).CloneVMTask.func1(0xc00153d380, 0x119a080, 0xc00153d380, 0xc0021a24e0, 0x2)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/virtual_machine.go:1588 +0x36e
github.com/vmware/govmomi/simulator.(*Task).Run(0xc00153d380, 0xc001d12800, 0xfe15dc, 0x7, 0xc000c5ef00)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/task.go:88 +0x150
github.com/vmware/govmomi/simulator.(*VirtualMachine).CloneVMTask(0xc001d12800, 0xc0037b22d0, 0xc002bf4d80, 0x0, 0x0)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/virtual_machine.go:1618 +0x4fd
reflect.Value.call(0xfd3240, 0xc001d12800, 0x213, 0xfdffff, 0x4, 0xc00249cf00, 0x2, 0x2, 0x9, 0xe, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xfd3240, 0xc001d12800, 0x213, 0xc00249cf00, 0x2, 0x2, 0xc001362160, 0x42e82a, 0xc001362213)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/vmware/govmomi/simulator.(*Service).call.func1()
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/simulator.go:216 +0x64
github.com/vmware/govmomi/simulator.(*Registry).WithLock(0xc0002ee360, 0x119a160, 0xc001d12800, 0xc0031fb738)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/registry.go:539 +0x37
github.com/vmware/govmomi/simulator.(*Service).call(0xc0017a5b60, 0xc0037b22d0, 0xc001f1a600, 0xe00, 0xc001f1a600)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/simulator.go:215 +0x60c
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc0017a5b60, 0x11a8280, 0xc0037c01c0, 0xc0028ba900)
	/home/centos/mock_vcenter/src/github.com/vmware/govmomi/simulator/simulator.go:472 +0x426
net/http.HandlerFunc.ServeHTTP(0xc001b18280, 0x11a8280, 0xc0037c01c0, 0xc0028ba900)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x1a2a560, 0x11a8280, 0xc0037c01c0, 0xc0028ba900)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc003544c40, 0x11a8280, 0xc0037c01c0, 0xc0028ba900)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000f4d9a0, 0x11a9dc0, 0xc000bd2040)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384```

**Comment by siddharth-kulshrestha** [comment]
@dougm Any help/solution would be appreciated.
