### ISSUE TITLE
vcsim: panic during ImportVApp for PCF OpsManager ova with custom inventory imported via -load

### ISSUE THREAD

**Issue by matthewcosgrove** [vmware/govmomi#1919]
IMPORTANT: This error is only reproducable after applying the fix remedied in #1915 

Using `ops-manager-vsphere-2.7.14-build.284.ova` I have observed

- `govc import.ova` successful on an actual vcenter lab
- `govc import.ova` fails on vcsim after loading the vcenter objects obtained from `object.save` against the lab mentioned above (See error below)

```bash
2020/04/08 07:43:07 http: panic serving 127.0.0.1:37338: runtime error: invalid memory address or nil pointer dereference
goroutine 114 [running]:
net/http.(*conn).serve.func1(0xc00067b7c0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xdc8d40, 0x19735a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/vmware/govmomi/simulator.(*VirtualMachine).Reference(0x0, 0x1, 0x1, 0xd5d480, 0x1157230)
	<autogenerated>:1 +0x44
github.com/vmware/govmomi/simulator.(*Folder).removeChild(0xc000a2fba0, 0x1198920, 0x0)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/folder.go:97 +0x35
github.com/vmware/govmomi/simulator.(*createVM).Run(0xc0007992a0, 0xc001032680, 0xc001032680, 0xc001e9ca80, 0x2, 0x2)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/folder.go:332 +0xe28
github.com/vmware/govmomi/simulator.(*Task).Run(0xc001032680, 0xc0007992a0, 0xc001032680, 0xc001f4b4f0, 0xc001f4acf0)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/task.go:88 +0x150
github.com/vmware/govmomi/simulator.(*Folder).CreateVMTask(0xc000a2fba0, 0xc001c846c0, 0xc001956900, 0xc00191d5b0, 0xa)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/folder.go:422 +0x84
github.com/vmware/govmomi/simulator.(*ResourcePool).ImportVApp(0xc0006ac2c0, 0xc001c846c0, 0xc000ee3080, 0x0, 0x0)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/resource_pool.go:207 +0x262
reflect.Value.call(0xf5d140, 0xc0006ac2c0, 0x1613, 0xfded9f, 0x4, 0xc001765a10, 0x2, 0x2, 0xc, 0xc, ...)
	/usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xf5d140, 0xc0006ac2c0, 0x1613, 0xc001765a10, 0x2, 0x2, 0xc000e57ce0, 0x42e82a, 0xc000e57d00)
	/usr/local/go/src/reflect/value.go:321 +0xb4
github.com/vmware/govmomi/simulator.(*Service).call.func1()
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/simulator.go:216 +0x64
github.com/vmware/govmomi/simulator.(*Registry).WithLock(0xc00030a2a0, 0x1198760, 0xc0006ac2c0, 0xc001f4b738)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/registry.go:551 +0x37
github.com/vmware/govmomi/simulator.(*Service).call(0xc00030aea0, 0xc001c846c0, 0xc001e53400, 0x1e00, 0xc001e53400)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/simulator.go:215 +0x60c
github.com/vmware/govmomi/simulator.(*Service).ServeSDK(0xc00030aea0, 0x11a6a20, 0xc0017aa540, 0xc001995b00)
	/home/matthew/go/src/github.com/vmware/govmomi/simulator/simulator.go:472 +0x426
```

**Comment by dougm** [comment]
Had started to look at this.. issue is the datastores point to a vmfs volume, rather that a local path.
