### ISSUE TITLE
govc unable to locate path via govc find

### ISSUE THREAD

**Issue by ChaoJJ** [vmware/govmomi#1947]
Hello Vmware team,

I'm currently trying to get govc to list all vms under a pool path, however it tells me that the path could not be found. I got that path via govc find -type p and even tested it with ls. The path exists.

the command looks like the following:
"govc find /datacenter/host/poolname/Resources -type m -dc=datacenter"

Normally I would also assume that I wouldn't even need to provide the dc flag, as its part of the path anyway, but then I only get the help response.

The command works for vcenter with only a single datacenter, but it doesn't work for me for this one vcenter that has multiple datacenters.

Anything I did wrong or is there a fix to this?

Otherwise if there is a simple way of attaining the resource pool name of every vm as a list and in a single request, similar to the response of "govc vm.info -r *", without individually requesting for every vm, please do tell. I'd much prefer it that way.

Thanks in advance

**Comment by dougm** [comment]
You shouldn't need `-dc`, that is optional to support relative paths. But when you do specify `-dc`, it needs to be before the ROOT arg: `govc find -dc dc1 /... -type m`

Is `/datacenter/host/poolname/Resources` one of the paths you see using `govc find / -type p` ?

For example against vcsim:

```console
% govc find / -type p
/DC0/host/DC0_H0/Resources
/DC0/host/DC0_C0/Resources

% govc find /DC0/host/DC0_H0/Resources -type m
/DC0/vm/DC0_H0_VM0
/DC0/vm/DC0_H0_VM1

% govc find /DC0/host/DC0_C0/Resources -type m
/DC0/vm/DC0_C0_RP0_VM0
/DC0/vm/DC0_C0_RP0_VM1
```

**Comment by ChaoJJ** [comment]
Indeed, ``/datacenter/host/poolname/Resources`` is what I get returned from the ``govc find -type p``. To be more exact I read out every line and feed it to the next call, which is ``govc find "extracted line" -type m``

Only reason I added the -dc bit (which I didn't know had to be before the path argument), was because govc didn't like my path.

What baffles me is that the code works for every other vcenter with a single datacenter, just not for the one with multiple vcenters. It refuses to recognize the path.

**Comment by ChaoJJ** [comment]
Now that I have provided the dc flag in the right place, govc says that the datacenter could not be found.
Just to make sure I ran ``govc find -type d`` and indeed, it is a valid datacenter.

**Comment by dougm** [comment]
Do you have the same issue using: `govc object.collect /datacenter/host/poolname/Resources` ?

**Comment by ChaoJJ** [comment]
Yes, issue persists with ``govc object.collect /datacenter/host/poolname/Resources``

**Comment by dougm** [comment]
Don't know what the issue is. But I could try to reproduce if you can provide a `govc object.save` tarball, see: https://github.com/vmware/govmomi/wiki/vcsim-features#record-and-playback
Email is dougm at vmware.

**Comment by ChaoJJ** [comment]
running ``govc object.save -u=my_vcenter_URL`` leaves me with a ``panic: reflect.Value.Addr of unaddressable value``, however I need to check with my corporate if sharing such a tarball falls in line with malpractice anyway.

**Comment by dougm** [comment]
Understood sharing the data might not be an option.  If there was a stacktrace with the panic, can you include that so we can see the code file:line where this happens?  And which version of govc are you using? git revision if built from source?

**Comment by ChaoJJ** [comment]
govc version is 0.22.1
revision number is ``cd4ce6bada4726dd827c35852e8ab0248462d959``
panic code is the following:
```
> govc object.save -u=vcenter_url

panic: reflect.Value.Addr of unaddressable value

goroutine 1 [running]:
reflect.Value.Addr(0x101a640, 0xc000388b60, 0x16, 0x146b800, 0x103ccc0, 0x16)
        c:/go/src/reflect/value.go:258 +0x9d
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x103ccc0, 0xc000376d10, 0x194, 0xc0003a4c40, 0xc000376d10, 0x194)
        C:/Users//go/src/github.com/vmware/govmomi/vim25/xml/read.go:371 +0x321a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf7c620, 0xc000070148, 0x197, 0xc0003a4c40, 0xc000070148, 0x197)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x2805
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000388960, 0x11d24e0, 0xc000070120, 0x199, 0x0, 0x0, 0x0, 0xc0003a4c40, 0x1, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x11d24e0, 0xc000070120, 0x199, 0xc0003a4880, 0xc000070120, 0x199)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf7e3a0, 0xc0003a4660, 0x197, 0xc0003a4880, 0xc0003a4660, 0x197)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x2805
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0003887e0, 0x11b1520, 0xc0003a4640, 0x199, 0x0, 0x0, 0x0, 0xc0003a4880, 0xc000523101, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xfea8a0, 0xc000115a90, 0x196, 0xc0003a4600, 0xc000115a90, 0x196)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0003885c0, 0x10dfd80, 0xc000115a40, 0x199, 0x0, 0x0, 0x0, 0xc0003a4600, 0x2030001, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x10dfd80, 0xc000115a40, 0x199, 0xc0003a42c0, 0x199, 0x10dfd80)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x103cc40, 0xc000376b50, 0x194, 0xc0003a42c0, 0xc000376b50, 0x194)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:359 +0x3192
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf7c5e0, 0xc000388508, 0x197, 0xc0003a42c0, 0xc000388508, 0x197)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x2805
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0005159e0, 0x10df1a0, 0xc000388500, 0x199, 0x0, 0x0, 0x0, 0xc0003a42c0, 0xc000524601, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x101a140, 0xc00019ac30, 0x196, 0xc0003a4140, 0xc00019ac30, 0x196)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000514900, 0x11f2d60, 0xc00019ac00, 0x199, 0x0, 0x0, 0x0, 0xc0003a4140, 0x1, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x11f2d60, 0xc00019ac00, 0x199, 0xc00028a340, 0x199, 0x11f2d60)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x10325e0, 0xc00007f070, 0x194, 0xc00028a340, 0xc00007f070, 0x194)
        C:/Users/johndoec/go/src/github.com/vmware/govmomi/vim25/xml/read.go:359 +0x3192
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000514540, 0x1225920, 0xc00007f040, 0x199, 0x0, 0x0, 0x0, 0xc00028a340, 0x603801, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x1225920, 0xc00007f040, 0x199, 0xc00043bf00, 0x199, 0x1225920)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x100c480, 0xc00019abd0, 0x194, 0xc00043bf00, 0xc00019abd0, 0x194)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:359 +0x3192
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000358680, 0x10e01e0, 0xc00019abc0, 0x199, 0x0, 0x0, 0x0, 0xc00043bf00, 0x1, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x10e01e0, 0xc00019abc0, 0x199, 0xc00043bd80, 0xc00019abc0, 0x199)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf7e4a0, 0xc000356480, 0x197, 0xc00043bd80, 0xc000356480, 0x197)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x2805
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0003141c0, 0x1198ba0, 0xc000356460, 0x199, 0x0, 0x0, 0x0, 0xc00043bd80, 0x1, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x1198ba0, 0xc000356460, 0x199, 0xc00043b700, 0xc000356460, 0x199)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf81960, 0xc000294130, 0x197, 0xc00043b700, 0xc000294130, 0x197)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x2805
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0003c01a0, 0x1166340, 0xc000294120, 0x199, 0x0, 0x0, 0x0, 0xc00043b700, 0xc000527501, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x1166340, 0xc000294120, 0x199, 0xc000296600, 0xc000294120, 0x199)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000412100, 0x107f060, 0xc000294120, 0x199, 0x0, 0x0, 0x0, 0xc000296600, 0xc000527ae8, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xf48b40, 0xc0003a6da8, 0x196, 0xc000296500, 0xc0003a6da8, 0x196)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc0004ff140, 0x11340c0, 0xc0003a6da0, 0x199, 0x0, 0x0, 0x0, 0xc000296500, 0xc000528088, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0xfd01c0, 0xc000124828, 0x194, 0xc0002963c0, 0xc000124828, 0x194)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc00019c240, 0xc000005d80, 0x1141140, 0xc000124800, 0x199, 0x0, 0x0, 0x0, 0xc0002963c0, 0xc000342255, ...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:771 +0x63a
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc00019c240, 0x1141140, 0xc000124800, 0x199, 0xc0002962c0, 0x199, 0x0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:583 +0x112b
github.com/vmware/govmomi/vim25/xml.(*Decoder).DecodeElement(0xc00019c240, 0xf394c0, 0xc000124800, 0x0, 0xc000296040, 0xae0000000129b8ed)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:151 +0x132
github.com/vmware/govmomi/vim25/xml.(*Decoder).Decode(...)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/xml/read.go:139
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip.func1(0xc000310000, 0x3582911b1, 0x1e901a0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/soap/client.go:625 +0xf1
github.com/vmware/govmomi/vim25/soap.(*Client).Do(0xc0003320b0, 0x1460c40, 0xc000245f50, 0xc000266500, 0xc000528e70, 0x0, 0x0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/soap/client.go:522 +0x2d5
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip(0xc0003320b0, 0x1460bc0, 0xc00002a0f8, 0x144cde0, 0xc0003a6d80, 0x144cde0, 0xc0003a6da0, 0xc0005f4ec0, 0x12)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/soap/client.go:613 +0x931
github.com/vmware/govmomi/vim25.(*retry).RoundTrip(0xc000314460, 0x1460bc0, 0xc00002a0f8, 0x144cde0, 0xc0003a6d80, 0x144cde0, 0xc0003a6da0, 0x1, 0xc0003a6da0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/retry.go:84 +0x91
github.com/vmware/govmomi/vim25.(*Client).RoundTrip(0xc000328580, 0x1460bc0, 0xc00002a0f8, 0x144cde0, 0xc0003a6d80, 0x144cde0, 0xc0003a6da0, 0x30, 0x10d8bc0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/client.go:129 +0x87
github.com/vmware/govmomi/vim25/methods.ContinueRetrievePropertiesEx(0x1460bc0, 0xc00002a0f8, 0x144c9c0, 0xc000328580, 0xc000245e60, 0x0, 0x0, 0x0)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/vim25/methods/methods.go:2299 +0xbf
github.com/vmware/govmomi/govc/object.(*save).Run(0xc0000b63c0, 0x1460bc0, 0xc00002a0f8, 0xc000070720, 0x0, 0x0)
        C:/Users/johndoec/go/src/github.com/vmware/govmomi/govc/object/save.go:272 +0xe6d
github.com/vmware/govmomi/govc/cli.Run(0xc00003a0d0, 0x2, 0x3, 0xc000078058)
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/govc/cli/command.go:165 +0x5e5
main.main()
        C:/Users/johndoe/go/src/github.com/vmware/govmomi/govc/main.go:98 +0x6b
```

**Comment by ChaoJJ** [comment]
putting the path as the last parameter in the find function worked, even after -type m.

However it has nothing to do with the panic. That problem still exists. But that doesn't concern me for the moment.
The main issue has been handled, so I will close the issue for now.

Thank you
