### ISSUE TITLE
VirtualMachine.UUID

### ISSUE THREAD

**Issue by spyroot** [vmware/govmomi#2046]
I think doesn't handle some edge cases.    I check VirtualMachine.UUID handles both nil cases but I think down the line the issue. 

2020-07-05T02:28:51.900039776Z stderr F goroutine 336 [running]:
2020-07-05T02:28:51.900052448Z stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1bfa2a0, 0x331b230)
2020-07-05T02:28:51.900059397Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
2020-07-05T02:28:51.900065626Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-07-05T02:28:51.900094938Z stderr F         /go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
2020-07-05T02:28:51.900101049Z stderr F panic(0x1bfa2a0, 0x331b230)
2020-07-05T02:28:51.900106853Z stderr F         /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-07-05T02:28:51.900114773Z stderr F github.com/vmware/govmomi/object.VirtualMachine.UUID(0x0, 0x0, 0xc0000d4840, 0xc000a40110, 0xe, 0xc000a40130, 0x6, 0x228e5a0,
0xc000638f60, 0x10, ...)

2020-07-05T02:28:51.900120341Z stderr F         /go/pkg/mod/github.com/vmware/govmomi@v0.23.0/object/virtual_machine.go:859 +0x1f7

**Comment by dougm** [comment]
Fixed in #2044 and https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/953
