### ISSUE TITLE
vcsim: PropertyCollector:propertyCollector does not implement: CheckForUpdates

### ISSUE THREAD

**Issue by aboudzz** [vmware/govmomi#2153]
from a Java VSphere client I'm trying to connect to a mocked VCenter I'm getting this error in my Java client:
```
com.vmware.vim25.MethodNotFound: PropertyCollector:propertyCollector does not implement: CheckForUpdates
        at jdk.internal.reflect.GeneratedConstructorAccessor124.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:254) ~[!/:?]
        at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:152) ~[!/:?]
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:110) ~[!/:?]
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:254) ~[!/:?]
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:97) ~[!/:?]
        at com.vmware.vim25.ws.VimStub.checkForUpdates(VimStub.java:114) ~[!/:?]
        at com.vmware.vim25.mo.PropertyCollector.checkForUpdates(PropertyCollector.java:71) ~[!/:?]
        ...
```

vcsim tells me that the method PropertyCollector.CheckForUpdates is not implemented.
```
$ $GOPATH/bin/vcsim
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=6599
yyyy/mm/dd HH:MM:SS PropertyCollector:propertyCollector does not implement: CheckForUpdates
```

**Comment by dougm** [comment]
We haven't implemented that method in vcsim yet, but we can add it.

**Comment by EatonEKia** [comment]
Hello,
Yes, having it will be really helpful.
Is it any way how we can help ?
Perhaps we may help to ass it. We are not experts of vcim internals nor Go experts.  May you provide us some entries where to start to look ?
TIA.
Bests

**Comment by embano1** [comment]
Let me know if this issue can be closed. `CheckForUpdates` is deprecated and has been superseded by `WaitForUpdates` which is already supported in the simulator code base.

https://vdc-download.vmware.com/vmwb-repository/dcr-public/723e7f8b-4f21-448b-a830-5f22fd931b01/5a8257bd-7f41-4423-9a73-03307535bd42/doc/vmodl.query.PropertyCollector.html#checkForUpdates

```
Deprecated. As of vSphere API 4.1, use WaitForUpdatesEx with a maxWaitSeconds of 0.
Checks for updates on properties specified by the union of all current filters. If no updates are pending, this method returns null.
```
