### ISSUE TITLE
Crash on vm.WaitForIP() timeout

### ISSUE THREAD

**Issue by mkuzmin** [vmware/govmomi#217]
I call vm.WaitForIP() method on a machine with no VMware Tools installed.
The method waits for 15 minutes (default timeout) and then crashes:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x64c96]

goroutine 36 [running]:
github.com/vmware/govmomi.(*Client).WaitForProperties(0xc208106580, 0xb650b0, 0xe, 0xc2081d6890, 0x8, 0xc208177b00, 0x1, 0x1, 0xc20813b668, 0x0, ...)
        /Users/mkuzmin/Projects/go/src/github.com/vmware/govmomi/client.go:174 +0x6b6
github.com/vmware/govmomi.VirtualMachine.WaitForIP(0xb650b0, 0xe, 0xc2081d6890, 0x8, 0x0, 0x0, 0xc208106580, 0x0, 0x0, 0x0, ...)
        /Users/mkuzmin/Projects/go/src/github.com/vmware/govmomi/virtual_machine.go:177 +0x14b
main.resourceVirtualMachineRead(0xc2081e2360, 0xaf1fa0, 0xc208106580, 0x0, 0x0)
        /Users/mkuzmin/Projects/go/src/github.com/mkuzmin/terraform-vsphere/resource_virtual_machine.go:149 +0x4f6
github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc20815ccf0, 0xc2081d3340, 0xaf1fa0, 0xc208106580, 0xc20815ad88, 0x0, 0x0)
        /Users/mkuzmin/Projects/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:166 +0x378
github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc20815cd50, 0xc2081d1380, 0xc2081d3340, 0x5fd280, 0x0, 0x0)
        /Users/mkuzmin/Projects/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:179 +0x1c7
github.com/hashicorp/terraform/rpc.(*ResourceProviderServer).Refresh(0xc20816e180, 0xc2081d65b0, 0xc2081d6a60, 0x0, 0x0)
        /Users/mkuzmin/Projects/go/src/github.com/hashicorp/terraform/rpc/resource_provider.go:341 +0x73
reflect.Value.call(0x840da0, 0xad5940, 0x13, 0xb21170, 0x4, 0xc20813bf28, 0x3, 0x3, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:419 +0x10e5
reflect.Value.Call(0x840da0, 0xad5940, 0x13, 0xc20813bf28, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:296 +0xbc
net/rpc.(*service).call(0xc20815e7c0, 0xc20815e780, 0xc208129d00, 0xc208113480, 0xc20816e1a0, 0x5fd220, 0xc2081d65b0, 0x16, 0x5fd280, 0xc2081d6a60, ...)
        /usr/local/go/src/net/rpc/server.go:382 +0x1f7
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:476 +0x44a

goroutine 1 [IO wait, 15 minutes]:
```

**Comment by pietern** [comment]
Thanks for the bug report. This is caused by the WaitForProperties function that expects the result to always be non-nil. It *is* nil, however, upon timing out. I think WaitForProperties should retry in this case, reissuing the WaitForUpdates call to the server. However, the user should have the ability to provide a timeout as well. I would like to use https://godoc.org/golang.org/x/net/context for this. What do you think? cc @dougm

**Comment by pietern** [comment]
By the way, cool to see you're working on a terraform plugin :+1:

**Comment by dougm** [comment]
The use of context has since been wired up and there should be no panic when timeout happens.  For example, see: `govc vm.ip -wait 1s $vm-without-tools`
