### ISSUE TITLE
VCSIM with yavijava giving exception while fetching serviceInstance.

### ISSUE THREAD

**Issue by Saiteja-Vangala** [vmware/govmomi#2365]
**GOVC simulator is working on terminal with vcsim.When I use vcsim  to integrate with yavijava sdk its giving below exception.Tried record and playback feature also but getting same exception.**
Exception in thread "main" java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is:
        java.lang.NoSuchFieldException: vStorageObjectManager
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:127)
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
        at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1675)
        at com.vmware.vim25.mo.ServiceInstance.retrieveServiceContent(ServiceInstance.java:246)
        at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:126)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:104)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:94)
        at TestVC.main(TestVC.java:30)
Caused by: java.lang.NoSuchFieldException: vStorageObjectManager
        at java.lang.Class.getField(Class.java:1695)
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:267)
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:240)
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:124)

**Comment by dougm** [comment]
What version of vCenter did you record?  I heard yavijava only supports 6.0, so if your vCenter is newer, try specifying the version and vCenter will exclude newer fields that don't apply to version 6:

```console
$ govc object.save -vim-version 6.0
```

**Comment by Saiteja-Vangala** [comment]
Hi ,Thanks for the reply .
Even after giving version 
govc object.save -vim-version 6.0.I am seeing vStorageObjectManager still present in the xml and same exception is being thrown.
 It is working if I manually comment the tag in xml from the recorded dump.

this is the line of code
ServiceInstance si = new ServiceInstance(url, "user", "pass",
				true, 30000, 1440);
