### ISSUE TITLE
com.vmware.vim25.MethodNotFound: AlarmManager:AlarmManager does not implement: GetAlarm

### ISSUE THREAD

**Issue by shyamala0713** [vmware/govmomi#2476]
When tried to fetch the configured alarms from VCenter simulator, alarm_manager.go file is not present in the simulator folder and hence GetAlarm method is not accessible.

com.vmware.vim25.MethodNotFound: AlarmManager:AlarmManager does not implement: GetAlarm
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:246)
        at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:149)
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:107)
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
        at com.vmware.vim25.ws.VimStub.getAlarm(VimStub.java:2551)
        at com.vmware.vim25.mo.AlarmManager.getAlarm(AlarmManager.java:162)

**Comment by dougm** [comment]
Right, simulator doesn't implement AlarmManager yet
