### ISSUE TITLE
Terraform apply fails for VM deployment using template with vcsim.

### ISSUE THREAD

**Issue by kumarom** [vmware/govmomi#2566]
**Describe the bug**
I want to use vcsim to test out our Terraform VM deployment for VMware using templates uploaded in vcsim.

This is follow up of #2558. Using the fix provided in #2558, I landed into another terraform panic issue.

**To Reproduce**
### Steps to Reproduce (on a Linux box)

1. Setup vcsim
```bash
# Used commit 6258af3ecc0f43e5130e075be224042f8abc84ca https://github.com/vmware/govmom and applied fix suggested by @dougm for #2558. Generated vcsim binary out of this code and used it for further steps.

$ vcsim
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=48828
```

2. At this point, open another terminal use this new terminal for rest of the instructions

3. Upload Template
```bash
$ govc version
govc 0.26.1

$ GOVC_INSECURE=1 GOVC_URL=https://user:pass@127.0.0.1:8989/sdk govc import.spec centos-7-7-template.ova | \
    jq '.NetworkMapping[0].Network = "VM Network" |
        .MarkAsTemplate = true |
        .Name = "centos-7-7-template"' > options.json
		
$ cat options.json
{
  "DiskProvisioning": "flat",
  "IPAllocationPolicy": "dhcpPolicy",
  "IPProtocol": "IPv4",
  "NetworkMapping": [
    {
      "Name": "bridged",
      "Network": "VM Network"
    }
  ],
  "MarkAsTemplate": true,
  "PowerOn": false,
  "InjectOvfEnv": false,
  "WaitForIP": false,
  "Name": "centos-7-7-template"
}

$ GOVC_INSECURE=1 GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_RESOURCE_POOL=/DC0/host/DC0_C0 govc import.ova -options=options.json centos-7-7-template.ova
[31-08-21 04:25:52] Uploading template-disk1.vmdk... OK
[31-08-21 04:25:52] Marking VM as template...

$ GOVC_INSECURE=1 GOVC_URL=https://user:pass@127.0.0.1:8989/sdk govc ls /DC0/vm
/DC0/vm/DC0_H0_VM0
/DC0/vm/DC0_H0_VM1
/DC0/vm/DC0_C0_RP0_VM0
/DC0/vm/DC0_C0_RP0_VM1
/DC0/vm/centos-7-7-template
```
4. Create a terraform file `main.tf` with below contents:
```hcl
terraform {
  required_providers {
    vsphere = {
      source = "hashicorp/vsphere"
      version = "2.0.2"
    }
  }
}

provider "vsphere" {
  vsphere_server = "127.0.0.1:8989"
  user           = "user"
  password       = "pass"
}

data "vsphere_datacenter" "datacenter" {
  name = "DC0"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "DC0_C0"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = "LocalDS_0"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = "centos-7-7-template"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "standalone" {
  lifecycle {
    ignore_changes = [clone.0.template_uuid]
  }

  name             = "CentOS 7.7 Test"
  resource_pool_id = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_id     = data.vsphere_datastore.datastore.id

  num_cpus = 4
  memory   = 12288
  guest_id = data.vsphere_virtual_machine.template.guest_id

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label            = "CentOS-7.7-Test.vmdk"
    size             = data.vsphere_virtual_machine.template.disks.0.size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks.0.eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks.0.thin_provisioned
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    linked_clone  = "false"
  }
}
```

5. Initialize Terraform and run `terraform plan`
```bash
$ wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
--2021-08-31 05:49:59--  https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
Length: 32416786 (31M) [application/zip]
Saving to: ‘terraform_1.0.5_linux_amd64.zip’

terraform_1.0.5_linux_amd64.zip                     100%[======================================================>]  30.92M  11.3MB/s    in 2.7s

2021-08-31 05:50:13 (11.3 MB/s) - ‘terraform_1.0.5_linux_amd64.zip’ saved [32416786/32416786]

$ unzip terraform_1.0.5_linux_amd64.zip
Archive:  terraform_1.0.5_linux_amd64.zip
  inflating: terraform

$ terraform version
Terraform v1.0.5 (linux_amd64)

$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/vsphere versions matching "2.0.2"...
- Installing hashicorp/vsphere v2.0.2...
- Installed hashicorp/vsphere v2.0.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

$ VSPHERE_ALLOW_UNVERIFIED_SSL=true terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.standalone will be created
  + resource "vsphere_virtual_machine" "standalone" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "/tmp/govcsim-DC0-LocalDS_0-342355689@group-5"
      + default_ip_address                      = (known after apply)
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + force_power_off                         = true
      + guest_id                                = "centos7_64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 12288
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "CentOS 7.7 Test"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 4
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-26"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + linked_clone  = false
          + template_uuid = "58201586-9e27-590c-a490-5bb1a404661f"
          + timeout       = 30
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "CentOS-7.7-Test.vmdk"
          + path              = (known after apply)
          + size              = 100
          + storage_policy_id = (known after apply)
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-7"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

6. vcsim response output on console

At this point, vcsim output since its start is as follows:
```bash
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=58223
2021/09/02 04:14:01 library not found: ""
```

Note: The `library not found: ""` is noticed only when `terraform plan` execution.

7. Terraform Apply
```bash
$ VSPHERE_ALLOW_UNVERIFIED_SSL=true terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.standalone will be created
  + resource "vsphere_virtual_machine" "standalone" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_id                            = "/tmp/govcsim-DC0-LocalDS_0-342355689@group-5"
      + default_ip_address                      = (known after apply)
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + force_power_off                         = true
      + guest_id                                = "centos7_64Guest"
      + guest_ip_addresses                      = (known after apply)
      + hardware_version                        = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + ide_controller_count                    = 2
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 12288
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "CentOS 7.7 Test"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 4
      + poweron_timeout                         = 300
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-26"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + sata_controller_count                   = 0
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + storage_policy_id                       = (known after apply)
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + linked_clone  = false
          + template_uuid = "58201586-9e27-590c-a490-5bb1a404661f"
          + timeout       = 30
        }

      + disk {
          + attach            = false
          + controller_type   = "scsi"
          + datastore_id      = "<computed>"
          + device_address    = (known after apply)
          + disk_mode         = "persistent"
          + disk_sharing      = "sharingNone"
          + eagerly_scrub     = false
          + io_limit          = -1
          + io_reservation    = 0
          + io_share_count    = 0
          + io_share_level    = "normal"
          + keep_on_remove    = false
          + key               = 0
          + label             = "CentOS-7.7-Test.vmdk"
          + path              = (known after apply)
          + size              = 100
          + storage_policy_id = (known after apply)
          + thin_provisioned  = true
          + unit_number       = 0
          + uuid              = (known after apply)
          + write_through     = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "network-7"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_virtual_machine.standalone: Creating...
╷
│ Error: Plugin did not respond
│
│   with vsphere_virtual_machine.standalone,
│   on main.tf line 32, in resource "vsphere_virtual_machine" "standalone":
│   32: resource "vsphere_virtual_machine" "standalone" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vsphere_v2.0.2_x5 plugin:

panic: runtime error: index out of range [-6]

goroutine 56 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/virtualdevice.NetworkInterfacePostCloneOperation(0xc0002be300, 0xc0006e8580, 0xc000263200, 0xe, 0x10, 0x0, 0xc0004ff800, 0x3, 0x4, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go:424 +0x252f
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachinePostDeployChanges(0xc0002be300, 0x14351a0, 0xc0008d9540, 0xc00071f180, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:1555 +0x931
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreateClone(0xc0002be300, 0x14351a0, 0xc0008d9540, 0x13cb5c0, 0xc00097b9c8, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:1478 +0x599
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreate(0xc0002be300, 0x14351a0, 0xc0008d9540, 0x6, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:322 +0x205
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004cce00, 0x19e30a8, 0xc000846380, 0xc0002be300, 0x14351a0, 0xc0008d9540, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004cce00, 0x19e30a8, 0xc000846380, 0xc0006d9260, 0xc00091a060, 0x14351a0, 0xc0008d9540, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c5e8, 0x19e30a8, 0xc000846380, 0xc0002cfa90, 0xc000846380, 0x16b5a40, 0xc000116f00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000707240, 0x19e3150, 0xc000846380, 0xc0006d9030, 0xc000707240, 0xc000116f60, 0xc000740ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x16b5a40, 0xc000707240, 0x19e3150, 0xc000116f60, 0xc000537f80, 0x0, 0x19e3150, 0xc000116f60, 0xc0002b5300, 0x11f1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000734000, 0x19ed138, 0xc000102780, 0xc0002f8d00, 0xc000116810, 0x233e2a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000734000, 0x19ed138, 0xc000102780, 0xc0002f8d00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00011c1d0, 0xc000734000, 0x19ed138, 0xc000102780, 0xc0002f8d00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vsphere/vendor/google.golang.org/grpc/server.go:857 +0x1fd

Error: The terraform-provider-vsphere_v2.0.2_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

8. vcsim response output on console

At this point, vcsim output since its start is as follows:
```bash
export GOVC_URL=https://user:pass@127.0.0.1:8989/sdk GOVC_SIM_PID=58223
2021/09/02 04:14:01 library not found: ""
2021/09/02 04:21:48 library not found: ""
2021/09/02 04:21:49 library not found: ""
2021/09/02 04:21:49 library not found: ""
```

Note: Additional three `library not found: ""` message that is generated only during `terraform apply` execution.

**Expected behavior**
* The `terraform apply` should have not panicked.
* `library not found: ""` message should not have appeared in vcsim output.

**Affected version**
vcsim version:
Used commit 6258af3ecc0f43e5130e075be224042f8abc84ca https://github.com/vmware/govmom and applied fix suggested by @dougm for #2558.

```bash
$ govc version
govc 0.26.1

$ terraform version
Terraform v1.0.5 (linux_amd64)
```

**Screenshots/Debug Output**
* [Terraform Apply Debug](https://gist.github.com/kumarom/3f7a4c8083a034c74d6a3950fd6e1c19)

**Additional context**
* #2558

**Comment by kumarom** [comment]
Just checking if there is any update on this..

**Comment by juancsr** [comment]
I'm looking forward to this issue be solved, getting same error here after creating a vm to be used as a template.


hey @kumarom did you have any news on this? :)

**Comment by kumarom** [comment]
> I'm looking forward to this issue being solved, getting the same error here after creating a VM to be used as a template.
> 
> hey @kumarom did you have any news on this? :)

No update so far.
