### ISSUE TITLE
[BUG] govmomi crashes in WaitForUpdateEx

### ISSUE THREAD

**Issue by parimanur** [vmware/govmomi#3018]
**Describe the bug**
We are seeing a crash in the WaitForUpdatesEx method. I am pasting the trace below.
```
panic: reflect.Value.Addr of unaddressable value
goroutine 332 [running]:
reflect.Value.Addr(0x451a840, 0xc003a1b280, 0x16, 0x599c800, 0x45b0f60, 0x16)
#011/usr/local/go/src/reflect/value.go:271 +0x85
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x45b0f60, 0xc0026063b0, 0x194, 0xc003a1b200, 0xc0026063b0, 0x194)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:371 +0x2fe6
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x41972a0, 0xc0039f12e8, 0x197, 0xc003a1b200, 0xc0039f12e8, 0x197)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x274d
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003a16740, 0x4ba8300, 0xc0039f12c0, 0x199, 0x0, 0x0, 0x0, 0xc003a1b200, 0x1, ...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:772 +0x568
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x4ba8300, 0xc0039f12c0, 0x199, 0xc003a1ae80, 0xc0039f12c0, 0x199)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:584 +0x1055
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x41990a0, 0xc003a1ac60, 0x197, 0xc003a1ae80, 0xc003a1ac60, 0x197)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x274d
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003a16640, 0x4a62ca0, 0xc003a1ac40, 0x199, 0x0, 0x0, 0x0, 0xc003a1ae80, 0xc003a1ab01, ...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:772 +0x568
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x44072a0, 0xc0039f0dd0, 0x196, 0xc003a1ac00, 0xc0039f0dd0, 0x196)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:584 +0x1055
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003a16480, 0x47a7a20, 0xc0039f0d80, 0x199, 0x0, 0x0, 0x0, 0xc003a1ac00, 0x1, ...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:772 +0x568
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x47a7a20, 0xc0039f0d80, 0x199, 0xc003a1a8c0, 0x199, 0x47a7a20)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:584 +0x1055
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x45b0ee0, 0xc002606130, 0x194, 0xc003a1a8c0, 0xc002606130, 0x194)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:359 +0x2f5b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x4197260, 0xc003a16428, 0x197, 0xc003a1a8c0, 0xc003a16428, 0x197)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:457 +0x274d
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003567dc0, 0x47a6e40, 0xc003a16420, 0x199, 0x0, 0x0, 0x0, 0xc003a1a8c0, 0xc003a1a601, ...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:772 +0x568
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x451a6c0, 0xc00360adb0, 0x196, 0xc003a1a740, 0xc00360adb0, 0x196)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:584 +0x1055
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003567000, 0x4cdc500, 0xc00360ad80, 0x199, 0x0, 0x0, 0x0, 0xc003a1a740, 0x1, ...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:772 +0x568
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x4cdc500, 0xc00360ad80, 0x199, 0xc003a0e940, 0x199, 0x4cdc500)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:584 +0x1055
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal(0xc000fc8d80, 0x4550640, 0xc00396eb70, 0x194, 0xc003a0e940, 0xc00396eb70, 0x194)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:359 +0x2f5b
github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshalPath(0xc000fc8d80, 0xc003566d20, 0x4dfe240, 0xc00396eb40, 0x199, 0x0, 0x0, 0x0, 0xc003a0e940, 0x401, ...)

...
...
github.com/vmware/govmomi/vim25/xml.(*Decoder).Decode(...)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/xml/read.go:139
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip.func1(0xc001c56a20, 0x1c6685244, 0x7a46880)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/soap/client.go:625 +0xf3
github.com/vmware/govmomi/vim25/soap.(*Client).Do(0xc0013bbd90, 0x59472d0, 0xc00112d3e0, 0xc001cb1900, 0xc003561ba8, 0x0, 0x0)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/soap/client.go:522 +0x35a
github.com/vmware/govmomi/vim25/soap.(*Client).RoundTrip(0xc0013bbd90, 0x5947260, 0xc0000760c8, 0x58aad60, 0xc000397440, 0x58aad60, 0xc000397458, 0x45a0201, 0xc000397458)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/soap/client.go:613 +0x905
github.com/vmware/govmomi/vim25.(*Client).RoundTrip(0xc0026c3340, 0x5947260, 0xc0000760c8, 0x58aad60, 0xc000397440, 0x58aad60, 0xc000397458, 0x62558f5, 0x4f)
#011/home/aviuser/workspace/21.1.6-ci-build/go/src/avi/vendor/github.com/vmware/govmomi/vim25/client.go:129 +0x82
github.com/vmware/govmomi/vim25/methods.WaitForUpdatesEx(0x5947260, 0xc0000760c8, 0x58a9680, 0xc0026c3340, 0xc003224e00, 0x0, 0x0, 0xc002b960c0)
```
**To Reproduce**

1. We are using the WaitForUpdatesEx to get the updates from the vcenter.
2. The code has been working in most of the environments but facing a crash in one of the setup.

**Expected behavior**
WaitForUpdatesEx should not crash.

**Affected version**
Please provide details on the version used, e.g. release tag, commit, module version, etc.

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**
Sample code which uses the WaitForUpdatesEx is below.
```
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	neturl "net/url"

	"github.com/vmware/govmomi"
	"github.com/vmware/govmomi/property"
	"github.com/vmware/govmomi/view"
	"github.com/vmware/govmomi/vim25"
	"github.com/vmware/govmomi/vim25/methods"
	"github.com/vmware/govmomi/vim25/mo"
	"github.com/vmware/govmomi/vim25/types"
)

const (
	maxWaitSeconds = 5
	// Page len for num of updates to recieve
	inventoryMaxObjectUpdates = 100
	SleepTimeInMilliSec       = 10

	username   = ""
	password   = ""
	host       = ""
	datacenter = ""
)

var (
	inventoryVmProperties = []string{"name", "config.vAppConfig",
		"config.uuid",
		"config.template",
		"runtime.powerState",
		"runtime.connectionState",
		"config.name",
		"config.hardware.device",
		"config.cpuAllocation",
		"config.memoryAllocation",
		"guest.net",
		"network"}
	inventoryNetworkProperties = []string{"name", "host"}
	inventoryDVPGProperties    = []string{"name", "host", "config"}
	inventoryHostProperties    = []string{"name", "parent",
		"network",
		"hardware.cpuInfo",
		"hardware.memorySize",
		"runtime.inMaintenanceMode",
		"runtime.connectionState",
		"runtime.powerState"}
	inventoryClusterProperties = []string{"name", "host"}
	finishedInitialUpdates     = "1"
)

func GetGovmomiClient() (*govmomi.Client, error) {
	u := &neturl.URL{Scheme: "https", Host: host, Path: vim25.Path}
	u.User = neturl.UserPassword(username, password)
	ctx := context.Background()
	client, err := govmomi.NewClient(ctx, u, true)
	if err != nil {
		return nil, err
	}
	return client, nil
}

func Stringify(serialize interface{}) string {
	json_marshalled, _ := json.Marshal(serialize)
	return string(json_marshalled)
}

// TestResourceDiscovery discovers DC, Host Network and clusters
func TestResourceDiscovery() {
	ctx := context.Background()
	client, err := GetGovmomiClient()
	if err != nil {
		log.Fatal(err)
	}
	pc := property.DefaultCollector(client.Client)
	pc, err = pc.Create(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer pc.Destroy(context.Background())
	dcMor := types.ManagedObjectReference{
		Type:  "Datacenter",
		Value: datacenter,
	}
	var dcDetails mo.Datacenter
	gvc, err := GetGovmomiClient()
	if err != nil {
		log.Fatal(err)
	}
	err = gvc.RetrieveOne(ctx, dcMor, nil, &dcDetails)
	if err != nil {
		log.Fatal(err)
	}
	m := view.NewManager(client.Client)
	v, err := m.CreateContainerView(ctx, dcMor, []string{"ClusterComputeResource", "HostSystem", "VirtualMachine", "Network", "DistributedVirtualPortgroup"}, true)

	if err != nil {
		log.Fatal(err)
	}

	objSpec := types.ObjectSpec{
		Obj: v.Reference(),
		SelectSet: []types.BaseSelectionSpec{
			v.TraversalSpec(),
		},
	}
	pspec := []types.PropertySpec{
		{
			Type:    "ClusterComputeResource",
			PathSet: inventoryClusterProperties,
		},
		{
			Type:    "HostSystem",
			PathSet: inventoryHostProperties,
		},
		{
			Type:    "VirtualMachine",
			PathSet: inventoryVmProperties,
		},
		{
			Type:    "Network",
			PathSet: inventoryNetworkProperties,
		},
		{
			Type:    "DistributedVirtualPortgroup",
			PathSet: inventoryDVPGProperties,
		},
	}

	filter := &property.WaitFilter{
		CreateFilter: types.CreateFilter{
			This: pc.Reference(),
			Spec: types.PropertyFilterSpec{
				ObjectSet: []types.ObjectSpec{
					objSpec,
				},
				PropSet: pspec,
			},
		},
		Options: &types.WaitOptions{
			MaxWaitSeconds:   types.NewInt32(maxWaitSeconds),
			MaxObjectUpdates: inventoryMaxObjectUpdates,
		},
	}
	err = pc.CreateFilter(ctx, filter.CreateFilter)
	if err != nil {
		log.Fatal(err)
	}
	req := types.WaitForUpdatesEx{
		This:    pc.Reference(),
		Options: filter.Options,
	}
	handler := func(updates []types.ObjectUpdate) {
		for _, update := range updates {
			fmt.Println(Stringify(update))
		}
	}
	// Run this continiously
	for {
		res, err := methods.WaitForUpdatesEx(ctx, client, &req)
		if err != nil {
			log.Fatal(err)
		}
		updateSet := res.Returnval
		if updateSet == nil {
			continue
		}
		req.Version = updateSet.Version
		fmt.Println("updateSet.Version: ", Stringify(updateSet.Version))
		for _, fs := range updateSet.FilterSet {
			handler(fs.ObjectSet)
		}

	}

}

func main() {
	TestResourceDiscovery()
}
```

**Comment by dougm** [comment]
What version of govmomi is used in the environment that crashes?
This looks like an issue that has been resolved, see: https://github.com/vmware/govmomi/issues/2694

**Comment by sourav12s** [comment]
v0.23.0 is used in the setup

**Comment by dougm** [comment]
You'll need to update govmomi to include [the fix](https://github.com/vmware/govmomi/pull/2219/commits/041a98b8c8f873ed297d11234c9238e95b732cbb) , release v0.24.1 or later (current is v0.30.0)

**Comment by parimanur** [comment]
@dougm Right, we suspected the same and generated the binary with v0.30.0, and the crash is not seen. But the reference of the issue helps us with the details where we can reproduce the issue. Thanks, closing the bug now.
