### ISSUE TITLE
vm.clone failing on Datastore.Path 

### ISSUE THREAD

**Issue by mgherman** [vmware/govmomi#561]
Hi,

I am attempting to clone a Template on ESXi 5.5 with govc 0.8.0, and am running into the following error:
```
mgh@us-nonprod-imgbuild-01:~$ ./govc vm.clone  -m 1024 -c 2 -dc Atlanta -folder='/Atlanta/vm/Non Production' -net="nonproduction" -pool '/Atlanta/host/Cluster 1/Resources/Staging' -on=false -vm="VM Images/Ubuntu/64-bit/12.04.5/mghTest" -host='/Atlanta/host/Cluster 1/us-prod-vmware-06.atl01.example.com' -ds='/Atlanta/datastore/ssd-nonproduction-vmfs-02' testing
panic: expected non-empty name

goroutine 1 [running]:
panic(0xe30a60, 0xc8204123e0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/vmware/govmomi/object.Datastore.Path(0x0, 0x0, 0xc820073900, 0xc820258e10, 0x9, 0xc820258e30, 0xf, 0xc820430500, 0x7, 0x0, ...)
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:72 +0xb7
github.com/vmware/govmomi/object.Datastore.Stat(0x0, 0x0, 0xc820073900, 0xc820258e10, 0x9, 0xc820258e30, 0xf, 0x7fd7e05aa400, 0xc82000e2c0, 0xc820430500, ...)
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:360 +0x35e
github.com/vmware/govmomi/govc/vm.(*clone).cloneVM(0xc82004b1e0, 0x7fd7e05aa400, 0xc82000e2c0, 0x0, 0x0, 0x0)
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:352 +0x14f9
github.com/vmware/govmomi/govc/vm.(*clone).Run(0xc82004b1e0, 0x7fd7e05aa400, 0xc82000e2b8, 0xc8200148a0, 0x0, 0x0)
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:192 +0x5f2
github.com/vmware/govmomi/govc/cli.Run(0xc82000a130, 0x10, 0x11, 0x162dbd0)
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/cli/command.go:139 +0x6ec
main.main()
	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/main.go:67 +0x60
```
Changing the `-ds` option to `ssd-nonproduction-vmfs-02` results in the same panic error message.
Omitting the `-ds` option results in:
```./govc: default datastore resolves to multiple instances, please specify```

Whilst I am sure that this is most likely user error, I have been unable to locate any examples of `vm.clone` to work from. 

Any pointers would be greatly appreciated.

Regards,

mgh

**Comment by mgherman** [comment]
This issue has been resolved with the latest merge of #563 Thanks! (Required an upgrade of Go to 1.7)
