### ISSUE TITLE
govc vm.clone crash

### ISSUE THREAD

**Issue by bradfitz** [vmware/govmomi#568]
I get a crash when trying to clone a VM:

```
$ govc vm.clone -ds=NetApp-1 OSX_10_11
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4de75f]

goroutine 1 [running]:
panic(0xb05020, 0xc4200100f0)
        /home/gopher/go/src/runtime/panic.go:500 +0x1a0
github.com/vmware/govmomi/govc/vm.(*clone).cloneVM(0xc42005eb60, 0x11b0bc0, 0xc4200102e8, 0x0, 0x1, 0x5)
        /home/gopher/src/github.com/vmware/govmomi/govc/vm/clone.go:249 +0xbf
github.com/vmware/govmomi/govc/vm.(*clone).Run(0xc42005eb60, 0x11b0bc0, 0xc4200102e0, 0xc42005c7e0, 0x0, 0x0)
        /home/gopher/src/github.com/vmware/govmomi/govc/vm/clone.go:194 +0x361
github.com/vmware/govmomi/govc/cli.Run(0xc42000c190, 0x3, 0x3, 0xc4200001a0)
        /home/gopher/src/github.com/vmware/govmomi/govc/cli/command.go:138 +0x484
main.main()
        /home/gopher/src/github.com/vmware/govmomi/govc/main.go:67 +0x66
```

It's crashing here:

```go
func (cmd *clone) cloneVM(ctx context.Context) (*object.Task, error) {

        // search for the first network card of the source
        devices, err := cmd.VirtualMachine.Device(ctx)  // <-----
```

And indeed, `cmd.VirtualMachine` is nil.

It seems that the lines right before the `cloneVM` call,

```go
        if cmd.VirtualMachine, err = cmd.VirtualMachineFlag.VirtualMachine(); err != nil {
                return err
        }
```

Returns `(nil, nil)`.

This is probably my fault, since I'm just starting to tinker with this, but the docs aren't particularly illustrative in how this is supposed to be used.

In particular, it doesn't even say that it accepts an argument:

```
$ govc vm.clone
Usage: govc vm.clone [OPTIONS]

Options:
  -c=0                          Number of CPUs
  -cert=                        Certificate [GOVC_CERTIFICATE]
  -customization=               Customization Specification Name
  -datastore-cluster=           Datastore cluster [GOVC_DATASTORE_CLUSTER]
  -dc=                          Datacenter [GOVC_DATACENTER]
  -debug=false                  Store debug logs [GOVC_DEBUG]
  -ds=                          Datastore [GOVC_DATASTORE]
  -dump=false                   Enable output dump
  -folder=                      Folder [GOVC_FOLDER]
  -force=false                  Create VM if vmx already exists
  -host=                        Host system [GOVC_HOST]
  -host.dns=                    Find host by FQDN
  -host.ip=                     Find host by IP address
  -host.ipath=                  Find host by inventory path
  -host.uuid=                   Find host by UUID
  -json=false                   Enable JSON output
  -k=true                       Skip verification of server certificate [GOVC_INSECURE]
  -key=                         Private key [GOVC_PRIVATE_KEY]
  -m=0                          Size in MB of memory
  -net=                         Network [GOVC_NETWORK]
  -net.adapter=e1000            Network adapter type
  -net.address=                 Network hardware address
  -on=true                      Power on VM
  -persist-session=true         Persist session to disk [GOVC_PERSIST_SESSION]
  -pool=                        Resource pool [GOVC_RESOURCE_POOL]
  -template=false               Create a Template
  -u=https://@10.88.203.10/sdk  ESX or vCenter URL [GOVC_URL]
  -vim-namespace=urn:vim25      Vim namespace [GOVC_VIM_NAMESPACE]
  -vim-version=6.0              Vim version [GOVC_VIM_VERSION]
  -vm=                          Virtual machine [GOVC_VM]
  -waitip=false                 Wait for VM to acquire IP address
```

I see `Usage: govc vm.clone [OPTIONS]` but no `<VM-NAME>` or whatever.

But the code definitely wants a VM name:

```go
func (cmd *clone) Run(ctx context.Context, f *flag.FlagSet) error {
        var err error

        if len(f.Args()) != 1 {
                return flag.ErrHelp
        }

        cmd.name = f.Arg(0)
```

**Comment by dougm** [comment]
We should add a Description() string method to the command ('git grep Example:' for examples).  And validate vm arg is given.  Try:

```
$ govc vm.clone -ds=NetApp-1 -vm OSX_10_11 new-osx-vm
```

**Comment by bradfitz** [comment]
I did figure it out as I wrote this bug report from reading the source.

I just wanted to point out both the crash, and that the docs are missing a bit.

**Comment by SciGno** [comment]
@bradfitz

So what was the solution to the crash?  

In my case, it crashed even when I specify the name.

**Comment by SciGno** [comment]
Sorry.  I forgot to paste the output:

```
govc vm.clone -c 2 -m 1024 -on=false -ds='/LA4 Datacenter/datastore/LUN 110 - R6_ML_DATASTORE10' -vm '/LA4 Datacenter/vm/Linux Templates/CentOS_6.8_Golden_Image' 'test'
panic: expected non-empty name

goroutine 1 [running]:
panic(0xe30a60, 0xc820406ba0)
       	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/vmware/govmomi/object.Datastore.Path(0x0, 0x0, 0xc820019b80, 0xc820236410, 0x9, 0xc820236430, 0xc, 0xc820406700, 0x4, 0x0, ...)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:72 +0xb7
github.com/vmware/govmomi/object.Datastore.Stat(0x0, 0x0, 0xc820019b80, 0xc820236410, 0x9, 0xc820236430, 0xc, 0x7f505b185400, 0xc82000e338, 0xc820406700, ...)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:360 +0x35e
github.com/vmware/govmomi/govc/vm.(*clone).cloneVM(0xc820051930, 0x7f505b185400, 0xc82000e338, 0x0, 0x0, 0x0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:352 +0x14f9
github.com/vmware/govmomi/govc/vm.(*clone).Run(0xc820051930, 0x7f505b185400, 0xc82000e330, 0xc82004e840, 0x0, 0x0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:192 +0x5f2
github.com/vmware/govmomi/govc/cli.Run(0xc82000a0c0, 0xa, 0xa, 0x162dbd0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/cli/command.go:139 +0x6ec
main.main()
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/main.go:67 +0x60
```

**Comment by dougm** [comment]
@SciGno looks #563 is the fix in your case

**Comment by SciGno** [comment]
@dougm 

Thanks for the reply but #563 did not fix my issue.  I'm sure the problem is on my side so I'm pasting as much information as possible in the hope that someone can correct me.

Any help will be greatly appreciated...

Thanks in advance...

``` bash
[root@cli1 ~]# env | grep GOVC
GOVC_NETWORK=/LOC Datacenter/network/(VLAN 272)
GOVC_HOST=/LOC Datacenter/host/App Cluster/host.domain.com
GOVC_PASSWORD=password
GOVC_INSECURE=true
GOVC_URL=https://some_ip/sdk
GOVC_DATACENTER=LOC Datacenter
GOVC_DATASTORE=/LOC Datacenter/datastore/LUN 110 - R6_ML_DATASTORE10
GOVC_VM=/LOC Datacenter/vm/Linux Templates/centos68
GOVC_USERNAME=domain\user
GOVC_FOLDER=/LOC Datacenter/vm/SharedVMs
GOVC_DEBUG=true

[root@cli1 ~]# govc ls datastore
/LOC Datacenter/datastore/LUN 110 - R6_ML_DATASTORE10
/LOC Datacenter/datastore/LUN 112 - R6_ML_DATASTORE11
/LOC Datacenter/datastore/Local Datastore esxi20
/LOC Datacenter/datastore/Local Datastore esxi21
/LOC Datacenter/datastore/Local Datastore esxi22
/LOC Datacenter/datastore/Local Datastore esxi23

[root@cli1 ~]# govc ls '*/Fusion Cluster'
/LOC Datacenter/host/Fusion Cluster/Resources
/LOC Datacenter/host/Fusion Cluster/sxi20.domain.com
/LOC Datacenter/host/Fusion Cluster/esxi21.domain.com
/LOC Datacenter/host/Fusion Cluster/esxi22.domain.com
/LOC Datacenter/host/Fusion Cluster/esxi23.domain.com

[root@cli1 ~]# govc vm.clone -force=false -c 2 -m 1024 -on=false myvm
panic: expected non-empty name

goroutine 1 [running]:
panic(0xe30a60, 0xc820406ba0)
       	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/vmware/govmomi/object.Datastore.Path(0x0, 0x0, 0xc820077900, 0xc820238400, 0x9, 0xc820238420, 0xc, 0xc820406700, 0x4, 0x0, ...)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:72 +0xb7
github.com/vmware/govmomi/object.Datastore.Stat(0x0, 0x0, 0xc820077900, 0xc820238400, 0x9, 0xc820238420, 0xc, 0x7f66a8302400, 0xc82000e328, 0xc820406700, ...)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/object/datastore.go:360 +0x35e
github.com/vmware/govmomi/govc/vm.(*clone).cloneVM(0xc820051a00, 0x7f66a8302400, 0xc82000e328, 0x0, 0x0, 0x0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:352 +0x14f9
github.com/vmware/govmomi/govc/vm.(*clone).Run(0xc820051a00, 0x7f66a8302400, 0xc82000e320, 0xc82004e840, 0x0, 0x0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/vm/clone.go:192 +0x5f2
github.com/vmware/govmomi/govc/cli.Run(0xc82000a0a0, 0x8, 0x8, 0x162dbd0)
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/cli/command.go:139 +0x6ec
main.main()
       	/Users/dougm/vmw/release/src/github.com/vmware/govmomi/govc/main.go:67 +0x60

```

**Comment by dougm** [comment]
@SciGno based on the line numbers in your stack trace, your govc build doesn't include the fix.  Note that the fix isn't included in the current release, so you'll need to build from source.  If you're using 'go get', make sure you include the '-u' flag to get the latest from git.

**Comment by SciGno** [comment]
@dougm 

Thanks for you help.  That worked.

**Comment by solarce** [comment]
I, also, had to `go get -u github.com/vmware/govmomi/govc` for `govc vm.clone -ds=/TravisCI/datastore/EMC-VMAX-2 -vm="/TravisCI/vm/Base/travis-ci-macos10.12-xcode8.1-1478207802" -pool=xServer_ESXi6 -net=dvPortGroup-Jobs test001` to work
