### ISSUE TITLE
crash in vm.change flag parsing

### ISSUE THREAD

**Issue by bradfitz** [vmware/govmomi#585]
```
gopher@godns:~$ govc vm.change -e guestinfo.key-darwin-amd64-10_10=xxxxxxxxxx -m=OSX_10_10
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53c329]

goroutine 1 [running]:
panic(0xb0e8c0, 0xc4200120a0)
	/home/gopher/go/src/runtime/panic.go:500 +0x1a0
github.com/vmware/govmomi/govc/flags.(*optionalBool).String(0xc420028180, 0xb9a720, 0xc420028180)
	/home/gopher/src/github.com/vmware/govmomi/govc/flags/optional_bool.go:43 +0x29
flag.isZeroValue(0xc42004d380, 0xce083d, 0x5, 0xd13bc9)
	/home/gopher/go/src/flag/flag.go:395 +0x12d
flag.(*FlagSet).PrintDefaults.func1(0xc42004d380)
	/home/gopher/go/src/flag/flag.go:469 +0x1d5
flag.(*FlagSet).VisitAll(0xc4200587e0, 0xc420049ae0)
	/home/gopher/go/src/flag/flag.go:325 +0x67
flag.(*FlagSet).PrintDefaults(0xc4200587e0)
	/home/gopher/go/src/flag/flag.go:478 +0x46
flag.defaultUsage(0xc4200587e0)
	/home/gopher/go/src/flag/flag.go:511 +0x96
flag.(*FlagSet).usage(0xc4200587e0)
	/home/gopher/go/src/flag/flag.go:827 +0x55
flag.(*FlagSet).failf(0xc4200587e0, 0xd088be, 0x21, 0xc420049dc8, 0x3, 0x3, 0xd500000000000038, 0x8)
	/home/gopher/go/src/flag/flag.go:816 +0x116
flag.(*FlagSet).parseOne(0xc4200587e0, 0x1, 0x0, 0x0)
	/home/gopher/go/src/flag/flag.go:899 +0x4d3
flag.(*FlagSet).Parse(0xc4200587e0, 0xc42000c0c0, 0x3, 0x3, 0xc4200c7228, 0xc400000001)
	/home/gopher/go/src/flag/flag.go:917 +0x60
github.com/vmware/govmomi/govc/cli.Run(0xc42000c0b0, 0x4, 0x4, 0xc4200001a0)
	/home/gopher/src/github.com/vmware/govmomi/govc/cli/command.go:130 +0x215
main.main()
	/home/gopher/src/github.com/vmware/govmomi/govc/main.go:69 +0x66
```

**Comment by bradfitz** [comment]
(Notably, I typoed `-vm=` as `-m=`)

The error in `govc/flags.(*optionalBool)` should've said I can't use OSX_10_10 as a bool instead of crashing.

Super low priority.

**Comment by dougm** [comment]
Looks like #577 - fix went in on Friday

**Comment by bradfitz** [comment]
Ah, great. Closing. Thanks!
