### ISSUE TITLE
Panic when running govc host.account.update -id root -password e2eFunctionalTest

### ISSUE THREAD

**Issue by mhagen-vmware** [vmware/govmomi#602]
Randomly saw this on a run of a bunch of functional tests we were running in Nimbus:

```
	'panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x79e1cc]

goroutine 1 [running]:
panic(0xb1c720, 0xc420012130)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/vmware/govmomi/object.HostConfigManager.AccountManager(0x0, 0x0, 0xc4201c2500, 0xc4202359e0, 0xa, 0xc420235a00, 0x7, 0x11ddf20, 0xc420012308, 0x54e8b1, ...)
	/Users/dougm/release/src/github.com/vmware/govmomi/object/host_config_manager.go:111 +0x1cc
github.com/vmware/govmomi/govc/host/account.(*AccountFlag).HostAccountManager(0xc420016c80, 0x11ddf20, 0xc420012308, 0x0, 0x0, 0xc42003de20)
	/Users/dougm/release/src/github.com/vmware/govmomi/govc/host/account/account.go:73 +0x232
github.com/vmware/govmomi/govc/host/account.(*update).Run(0xc42002a0f0, 0x11ddf20, 0xc420012308, 0xc42000aa80, 0x0, 0x0)
	/Users/dougm/release/src/github.com/vmware/govmomi/govc/host/account/update.go:47 +0x49
github.com/vmware/govmomi/govc/cli.Run(0xc42000a250, 0x5, 0x5, 0xc4200001a0)
	/Users/dougm/release/src/github.com/vmware/govmomi/govc/cli/command.go:149 +0x586
main.main()
	/Users/dougm/release/src/github.com/vmware/govmomi/govc/main.go:69 +0x66' should be empty.
```

**Comment by dougm** [comment]
Where you running against 5.5 in this case?  Not sure what else would cause the issue, but we should avoid the panic in any case.

**Comment by mhagen-vmware** [comment]
No 5.5.  6.0u2
