### ISSUE TITLE
vcsim: parse error while removing snapshot

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#859]
```
# python test_vm_snapshot.py
Traceback (most recent call last):
  File "test_vm_snapshot.py", line 48, in <module>
    main()
  File "test_vm_snapshot.py", line 40, in main
    snap_obj = get_snapshots_by_name_recursively(vm.snapshot.rootSnapshotList, 'smk')
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/Volumes/data/src/ansible/venv4/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1357, in InvokeMethod
    raise exc
pyVmomi.SoapAdapter.ParserError: 'xml document: <httplib.HTTPResponse instance at 0x1074d7b00> parse error at: line:2, col:857'
```

Testcase to reproduce this with the most current version of pyvmomi (6.5.0.2017.5.post1)

```python
#!/usr/bin/env python
import ssl

from pprint import pprint
from pyVim import connect
from pyVmomi import vim


def get_obj(content, vimtype, name):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj = c
            break

    return obj

def get_snapshots_by_name_recursively(snapshots, snapname):
    snap_obj = []
    for snapshot in snapshots:
        if snapshot.name == snapname:
            snap_obj.append(snapshot)
        else:
            snap_obj += get_snapshots_by_name_recursively(snapshot.childSnapshotList, snapname)
    return snap_obj

def main():
    service_instance = connect.SmartConnect(host='127.0.0.1', port=443, user='user', pwd='pass')
    content = service_instance.RetrieveContent()
    vm = get_obj(content, [vim.VirtualMachine], 'DC0_H0_VM0')
    snap_obj = get_snapshots_by_name_recursively(vm.snapshot.rootSnapshotList, 'snapshot_0001')
    snap_obj.RemoveSnapshot_Task(False)

if __name__ == "__main__":
    main()
```

**Comment by dougm** [comment]
@Akasurde thanks, I can reproduce with your script.  We are missing some required fields, I'm fixing now @anfernee is out today.
