### ISSUE TITLE
vcsim: dvswitch list index out of range in pyvmomi

### ISSUE THREAD

**Issue by jctanner** [vmware/govmomi#879]
```
The full traceback is:
  File "/tmp/ansible_2FXA_E/ansible_module_vmware_dvswitch.py", line 130, in process_state
    dvs_states[self.state][self.check_dvs_configuration()]()
  File "/tmp/ansible_2FXA_E/ansible_module_vmware_dvswitch.py", line 184, in check_dvs_configuration
    self.dvs = find_dvs_by_name(self.content, self.switch_name)
  File "/tmp/ansible_2FXA_E/ansible_modlib.zip/ansible/module_utils/vmware.py", line 160, in find_dvs_by_name
    vmware_distributed_switches = get_all_objs(content, [vim.dvs.VmwareDistributedVirtualSwitch])
  File "/tmp/ansible_2FXA_E/ansible_modlib.zip/ansible/module_utils/vmware.py", line 434, in get_all_objs
    for managed_object_ref in container.view:
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 43, in InvokeAccessor
    objectContent = result.objects[0]

failed: [testhost] (item=/F0/DC0) => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "datacenter_name": "DC0",
            "discovery_operation": "both",
            "discovery_proto": "lldp",
            "hostname": "localhost",
            "mtu": 9000,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "switch_name": "dvswitch_0001",
            "uplink_quantity": 2,
            "username": "user",
            "validate_certs": false
        }
    },
    "item": "/F0/DC0",
    "msg": "list index out of range"
}
```

I can't tell if this is the fault of pyvmomi or from vcsim's response to the request. If pyvmomi needs to be fixed, i'm more than happy to move the bug over to that project. I just need some guidance on making that determination.

**Comment by jctanner** [comment]
[vcsim.log](https://github.com/vmware/govmomi/files/1388327/vcsim.log)

vcsim log output with -trace

**Comment by dougm** [comment]
In 3f145230 we changed `VmwareDistributedVirtualSwitch` to `DistributedVirtualSwitch`.  We could revert the simulator portion of that change, or maybe you could change the get_all_objs call to use `vim.dvs.DistributedVirtualSwitch` instead of `vim.dvs.VmwareDistributedVirtualSwitch` ?

**Comment by jctanner** [comment]
@dougm that doesn't seem to be a valid type for pyvmomi ...

```shell
[jtanner@ansidev AP-FIX_VCSIM]$ python
Python 2.7.13 (default, Sep  5 2017, 08:53:59)
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyvmomi import vim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyvmomi
>>> from pyVmomi import vim
>>> vim.dvs.VmwareDistributedVirtualSwitch
<class 'pyVmomi.VmomiSupport.vim.dvs.VmwareDistributedVirtualSwitch'>
>>> vim.dvs.DistributedVirtualSwitch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 262, in __getattr__
    raise AttributeError(attr)
AttributeError: DistributedVirtualSwitch
```

**Comment by dougm** [comment]
@jctanner looks like it's just `vim.DistributedVirtualSwitch`, rather than `vim.dvs.VmwareDistributedVirtualSwitch` - does that work for you?

**Comment by jctanner** [comment]
@dougm yep, that works. Thank you
