### ISSUE TITLE
Crash in Task.Wait after operation blocked by license

### ISSUE THREAD

**Issue by vancluever** [vmware/govmomi#896]
Hey all,

Got this in terraform-providers/terraform-provider-vsphere#223 this morning:

```
2017-10-25T12:00:51.229+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 2017/10/25 12:00:51 [DEBUG] datastore: "datastore1"
2017-10-25T12:00:51.361+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 2017/10/25 12:00:51 [ERROR] ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: panic: runtime error: invalid memory address or nil pointer dereference
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdde937]
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: goroutine 12 [running]:
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/vmware/govmomi/object.(*Task).WaitForResult(0x0, 0x1dcfb00, 0xc420016130, 0x0, 0x0, 0x11a42a0, 0x0, 0x1dcfb00)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/vmware/govmomi/object/task.go:52 +0x37
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/vmware/govmomi/object.(*Task).Wait(0x0, 0x1dcfb00, 0xc420016130, 0x1dcfb00, 0xc420016130)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/vmware/govmomi/object/task.go:47 +0x51
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.(*virtualMachine).setupVirtualMachine(0xc42026c540, 0xc4203a6440, 0x5, 0xff05e0)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:2114 +0x4ca6
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineCreate(0xc4202382a0, 0x1079620, 0xc4203a62a0, 0x24, 0x1e3aac0)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:1018 +0x1f81
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203492c0, 0xc42043c0f0, 0xc420540ae0, 0x1079620, 0xc4203a62a0, 0x1, 0xc4204f8630, 0x0)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x3b6
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4203e0fc0, 0xc42043c050, 0xc42043c0f0, 0xc420540ae0, 0x7f1da1e87000, 0x0, 0x18)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xa4
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420379ac0, 0xc4205406c0, 0xc4203ba2b0, 0x0, 0x0)
2017-10-25T12:00:51.364+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
```

Any thoughts right off the bat? Seems like whatever they were trying to do (create a VM) was blocked due to license restrictions and then caused a crash.

Let me know!

**Comment by dougm** [comment]
In this case you probably want to `return err` as `task` will be nil `if err != nil`:
https://github.com/terraform-providers/terraform-provider-vsphere/blob/eb9a0ad0a0f80048cd3adc407c6e18e8f4d01f56/vsphere/resource_vsphere_virtual_machine.go#L2109-L2112

**Comment by vancluever** [comment]
Sigh, thanks and sorry @dougm, should have looked at that bit further :stuck_out_tongue: 

Closing now
