### ISSUE TITLE
vcsim fails when MakeDirectory is called

### ISSUE THREAD

**Issue by Akasurde** [vmware/govmomi#937]
When trying to create a directory inside datastore with `vim.fileManager.MakeDirectory` API, vcsim fails with "RuntimeFault" with no message.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_U85NQx/ansible_module_vmware_guest.py", line 1684, in <module>
    main()
  File "/tmp/ansible_U85NQx/ansible_module_vmware_guest.py", line 1673, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_U85NQx/ansible_module_vmware_guest.py", line 1382, in deploy_vm
    self.configure_disks(vm_obj=vm_obj)
  File "/tmp/ansible_U85NQx/ansible_module_vmware_guest.py", line 1103, in configure_disks
    self.content.fileManager.MakeDirectory(name=path_on_ds)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.RuntimeFault: (vmodl.RuntimeFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

`self.content.fileManager.MakeDirectory(name=path_on_ds)` works on ESXi but does not work for vcsim.

Reproducer Ansible PR - https://github.com/ansible/ansible/pull/33230

**Comment by Akasurde** [comment]
```
(Pdb) content.fileManager.MakeDirectory("[LocalDS0] b")
*** vmodl.RuntimeFault: (vmodl.RuntimeFault) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```
